### ISSUE TITLE
Forth handling is welcome, but confusing and a bit buggy

### ISSUE THREAD

**Issue by rrthomas** [AlDanial/cloc#103]
I just upgraded from cloc 1.60 to 1.68 while trying to get it to handle Forth, and was happy to find that Forth has been added in the mean time.

There are a few oddities, however:

1. ".fs" extension is missing (however, my .fs extension files were recognised as Forth, no problem, I guess because of the special logic for Forth).
2. One Forth comment style is given as "remove_between_general (* *)". I have never heard of this being used in Forth, in 30 years. (It is used in Coq, or indeed in ML, which is not (yet) handled by cloc.) Even more confusingly, if I put this comment style in a Forth program, it is not recognised as a comment by cloc (again, is this because of the special logic?).
3. Finally, the "long comment" style that Forth DOES use is "( ... )", i.e. plain parens. I was trying to work out how to add this, and I couldn't, primarily because in Forth they don't nest. Also, space is required before and after the opening "(", because in Forth "(" is not special syntax, but just a normal word that is called (it then discards everything up to and including the next ")", meaning that the closing ")" does not need space before or after it).

I was experimenting with the language definition, but because it seems to be at least partly overridden by the special logic now in cloc, I'm a bit lost, and could do with some help in sorting this out.

The upshot of all the above is that cloc works fine on single-line comments ("\" to end of line, and "(...)" within a line), but not on long multiline comments.

I continue to be delighted by cloc (and in particular on this occasion, seeing that most of the work for Forth has already been done)!

**Comment by AlDanial** [comment]
Thanks for your comments and for sticking with cloc all these years.  Actually, fs is a recognized extension for Forth in v1.68:
<pre>
> ./cloc-1.68.pl --explain Forth
Forth
    filter remove_matches  (^|\s)\\\s.*$
    filter remove_matches  (^|\s)\(\s.*?\)
    filter remove_between_general  (*  *)
    extensions: 4th, e4, f83, fb, forth, fpm, fr, frt, ft, fth, rx, fs, f, for
</pre>

The complication is that fs is also shared with the F# language and so a disambiguator had to be written for these two languages.

Regarding the existing comment filters for Forth, those were provided by  @larsbrinkhoff
for issue #20 (https://github.com/AlDanial/cloc/issues/20). I know little about Forth and so am not qualified to adjudicate the discrepancy between his post and yours.  Possibly (* .. *) is recognized by a flavor of Forth compiler (interpreter?) Lars uses.

In any event, I downloaded some sample Forth code and found that you're right, cloc is unable to handle Forth multiline comments.  In a few moments I will commit a change to fix this, and also to implement the space, open paren, space form of comment handling since none of the examples I found used the Pascal notation.  For completeness I'll email Lars and ask him for his thoughts on the matter.

**Comment by larsbrinkhoff** [comment]
Hello @rrthomas,

I don't have 30 years of Forth experience, so I welcome your input on this.  My intention was that `(*` and `*)` should be used for multi-line, *nested* comments.  Those aren't standard in Forth, but it was my impression that `(*` and `((` are somewhat common for that purpose, with the first being a bit more common.

**Comment by rrthomas** [comment]
@larsbrinkhoff thanks very much: my experience with Forth is largely "old-fashioned", so that's probably why I missed the new nesting comment styles.

It sounds as though I missed the ".fs" suffix because it is allocated to F# in the language definitions.

@AlDanial, thanks so much for the prompt fix for (…) comments. I will test now and report back.

**Comment by rrthomas** [comment]
After that commit things are working much better, not least because with 1.68 all lines containing a "\" comment are stripped, even if they also contain code (I hadn't noticed!).

**Comment by AlDanial** [comment]
If cloc in its current state meets your expectations for Forth, can this issue be closed?  Nested comments as described by @larsbrinkhoff aren't implemented.  If either of you want additional features, please post a Forth file demonstrating cloc's shortcomings and I'll work on it.

**Comment by larsbrinkhoff** [comment]
Thank you @AlDanial.  I think cloc is good enough for now.  Those nested comments are rare.
