### ISSUE TITLE
Summary by Folder

### ISSUE THREAD

**Issue by gregwillits** [AlDanial/cloc#122]
Perhaps I'm just not seeing where this is documented, but a summary by folder would be useful to understand the sizes of code "modules." Folder alone would be OK, with an option to summarize by file type per folder being even better. Thanks for all your work.

**Comment by AlDanial** [comment]
"Folder alone would be OK":  cloc can already count everything recursively below a directory or folder; just give it the directory name.  Summaries are given by programming language.  On Windows this might look like
<pre>
  cloc.exe c:\src\module_1
</pre>
I'm not keen on adding a summary by folder option because there many different ways to organize projects; having cloc descend the directories and report on the contents at each level strikes me as only marginally useful capability.  Also, on Unix & Mac at least, such a task can accomplished with the<tt>find</tt> and <tt>xargs</tt> commands.
