### ISSUE TITLE
Plugin for Grunt task runner

### ISSUE THREAD

**Issue by jolkdarr** [AlDanial/cloc#13]
It would be nice if cloc could be automatically launched from [Grunt](http://gruntjs.com/) with relevant options.

Note. _if you think I'm using Grunt, you're right ;)_
Grunt plugins are available for Sloc, Sloccount and file-sloc.

**Comment by AlDanial** [comment]
Help me out here... what changes to cloc are needed for it to work with Grunt?  I don't know anything about Grunt or Grunt plugins.

**Comment by jolkdarr** [comment]
I think the `cloc` tool doesn't need to be modified.
I suggested there that a plugin wrapping `cloc` execution might be useful.
That Grunt plugin should be provided as an add-on in a separate project (`grunt-contrib-cloc`).

A short article describes well the work implied for such task at:
http://javascriptplayground.com/blog/2014/01/creating-your-first-grunt-plugin/

Note that another build system may be selected instead (gradle, ant...).
I will try to give more information this week-end.

**Comment by AlDanial** [comment]
Interesting.  Sadly I know little javascript or how to set up an environment to develop and test the plug-in.  I'm sure with enough time I could do it, but time is precious, already spread too thin.  I'm happy to accept pull requests for such a tool though.

**Comment by AlDanial** [comment]
Just re-read your first note, "Grund plugins are available for ... Sloccount".  I will download that one and see if a cloc equivalent can be made by s/sloccount/cloc/.

**Comment by AlDanial** [comment]
OK, here's a naive version of grunt-cloc, made by copying the content of https://github.com/asciidisco/grunt-sloccount and replacing tool names.  Let me know if even remotely works.

(Since github doesn't allow attaching tar files, I converted the compressed tar to text with uuencode.  To get the files, do uudecode grunt-cloc.tar.bz2.txt, then unzip the tar file.)
[grunt-cloc.tar.bz2.txt](https://github.com/AlDanial/cloc/files/23044/grunt-cloc.tar.bz2.txt)

**Comment by jolkdarr** [comment]
I have suggested a yet simpler plugin.
I will provide the Grunt plugin in a separate git repository since the two projects are quite independent and the plugin is to be published as a Node package:
```sh
npm publish
```
