### ISSUE TITLE
Ignore git submodules when vcs=git 

### ISSUE THREAD

**Issue by cirosantilli** [AlDanial/cloc#131]
Possibly a better default, or maybe another configuration...

`git ls-files` includes them.

The best I have is:

```
git ls-files | grep -Fxvf <(git submodule status | cut -d' ' -f3)
```

with current workaround:

```
cloc --list-file=<(git ls-files | grep -Fxvf <(git submodule status | cut -d' ' -f3)) .
```

Also: http://stackoverflow.com/questions/40165650/how-to-list-all-files-tracked-by-git-excluding-submodules

**Comment by cirosantilli** [comment]
Non minimal: https://github.com/lowRISC/lowrisc-chip

But I'd also recommend manual creation of a submodule with two local repos.

**Comment by AlDanial** [comment]
I'm looking at your command a piece at a time to understand what's going on.  If I do
<pre>git submodule status | cut -d' ' -f3</pre> in the lowrisc-chip directory I get a bunch of empty lines.  But if I cut field 2 instead of 3 with <pre>git submodule status | cut -d' ' -f2</pre> then I get
<pre>
chisel
context-dependent-environments
fpga
hardfloat
junctions
opensocdebug/glip
opensocdebug/hardware
opensocdebug/software
riscv-tools
rocket
socip
uncore
</pre>

Isn't that what the subexpression should do?  If <code>-f3</code> is correct, could you explain what the intent is?

**Comment by cirosantilli** [comment]
Yes, that is the expected output.

Must be a difference between our Gits / cut.

On Ubuntu 16.04, git 2.7.0, `cut` coreutils 8.25 `cut -f3` works because `git` outputs a space at the beginning of every line for some reason.

**Comment by AlDanial** [comment]
Kind of worrying that it is so sensitive to git version.  I'm on Ubuntu 16.04, git 2.7.4, coreutils 8.25.
The cut manpage suggests there isn't a way to say "the last column".  Perl can do so however.  This will be more portable:
<pre>
git submodule status | perl -ane 'print"$F[$#F]\n"'
</pre>
I have other commitments over the next few days but will try to get this added soon.

**Comment by cirosantilli** [comment]
Weird.

Another option is ignore directories of the output of `git ls-files`.

**Comment by AlDanial** [comment]
Ignoring directories from the output of <code>git ls-files</code> isn't the right thing to do; nearly every git repo I know of has subdirectories which are not part of a submodule.

I'm unable to use <code>git ls-files | grep -Fxvf <(git submodule status | perl -ane 'print"$F[$#F]\n"')</code> as a single expression in cloc, get a shell error, probably because of the < redirection.  I'll have to split it into multiple commands and parse the output myself which is kind of a drag.

I also wonder if current users of both git and cloc want to count, rather than skip, the code in submodules?  Would this new behavior give them mysteriously fewer results?  Perhaps a better solution is for me to post your work-around (<code>--list-file=...</code>) in the documentation instead of baking it into cloc.

**Comment by cirosantilli** [comment]
@AlDanial ignore directories: git only tracks files (OK, there is the empty directory, but it's useless). `git ls-files` only shows files and submodules. I didn't mean to ignore all subdirectories!

Yes, that command is only for illustration. You should of course parse `git ls-files`. Or better: use some existing Perl wrapper that uses libgit2 to do it for you.

Default: yes, this is totally subjective, and I will not argue with it :-) That is what I meant by "Possibly a better default, or maybe another configuration"

All I can say is that for me it would be more meaningful: submodules represent external repositories, so generally for me they represent complexity which does not belong to my project, much like external libraries in Perl.

**Comment by AlDanial** [comment]
I implemented the 'git submodule status' filter in a new branch called <code>gitsubmodule</code>.  It isn't a perfect solution (the correct solution actually requires me fix to issue #132 first) but should work fine in nearly all cases.  (It will do the wrong thing only if one of the submodule names also appears as a directory name in the original repository, but lower down in the directory tree.)

Please fetch this branch and try it out, let me know if it works as you expect.  In the meantime I will grab a few more large repos with submodules and try it too.

**Comment by AlDanial** [comment]
The fix is in the master branch.

**Comment by sjjctl** [comment]
Is there any way to force the inclusion of submodules in the count?

**Comment by AlDanial** [comment]
There's not a clean way at the moment.  If you're working with the source version of cloc you can comment out the loop at lines 1104 to 1110 in the current git version:

```
 1101     if      ($opt_vcs eq "git") {
 1102         $opt_vcs = "git ls-files";
 1103         my @submodules = invoke_generator('git submodule status');
 1104         foreach my $SM (@submodules) {
 1105             $SM =~ s/^\s+//;        # may have leading space
 1106             $SM =~ s/\(\S+\)\s*$//; # may end with something like (heads/master)
 1107             my ($checksum, $dir) = split(' ', $SM, 2);
 1108             $dir =~ s/\s+$//;
 1109             $Exclude_Dir{$dir} = 1;
 1110         }
```

For a clean solution please open a new issue.
