### ISSUE TITLE
"Complex regular subexpression recursion limit (32766) exceeded" for gradle build file

### ISSUE THREAD

**Issue by filippucher1** [AlDanial/cloc#139]
Problem: this fragment of gradle build file causes recursion limit exceeded
```groovy
war {
    from ('src') {
        exclude 'com/**'
        exclude 'org/**'
        into '/WEB-INF/classes'
    }
}
war.dependsOn longStringTypedHere
eclipse {
    wtp {
        component {
            resource sourcePath: "$WEBDIR_NAME", deployPath: "/"
        }
    }
}
tasks.eclipse.dependsOn longStringTypedHere
```

Symptoms:
When I remove double asterisks `**` from `exclude 'com/**'` 
or when I shorten any of `longStringTypedHere` by 2 characters to, e.g. `longStringTypedHe` 
or when I remove whichever entire line 
then issue is gone.

Using cloc version `1.71` from Nov 4, 2016, commit cbf61f98c5cfddba41e6a82ea7973b3fdf35d59e
ActiveState binary build 2400 built Jun 9 2016 21:44:59, perl version `5.24.0`, Windows 7 64bit
File build.gradle uses `LF` only as line delim

**Comment by AlDanial** [comment]
Thanks for the precise bug report.  The issue was caused by <code>`/**`</code> on the <tt>exclude</tt> lines.  Since Groovy allows C++ style comments these characters were viewed by cloc as the start of C++ comments that were never terminated.  I added a command to remove <tt>`/**`</tt> from Groovy files before going to the C++ comment parser.
