### ISSUE TITLE
"Complex regular subexpression recursion limit (32766) exceeded" for java file

### ISSUE THREAD

**Issue by filippucher1** [AlDanial/cloc#140]
Problem: this fragment causes recursion limit exceeded

```java
@Controller
@RequestMapping( "/security/*" )
public class SecurityController {
```
Inspired by your Issue #139 solution, I've identified the cause as this character sequence `/*`
Paraphrasing your words "Since Java allows C++ style comments these characters are viewed by cloc as the start of C++ comments that were never terminated."

I've added a command to remove `/*` from Java files before going to the C++ comment parser and voila the issue is gone.

Proposed solution:
```perl
    'Java'   => [
#                      [ 'remove_matches'      , '^\s*//' ],
                       [ 'remove_between_regex', '/\*', '$' ],     <----- added command here
                       [ 'call_regexp_common'  , 'C++'    ],
                       [ 'remove_inline'       , '//.*$'  ],
                ],
```

**Comment by AlDanial** [comment]
It's a good idea, but unfortunately won't work because this will mess up legitimate `/*` .. `*/` comments, essentially uncommenting the innards and making them look like code.  My solution to #139 also fails in cases where someone has a C comment that starts with `/**`.

A big part of the problem is that cloc (actually cloc's reliance on the Perl Regexp::Common::Comment module) doesn't recognize that these markers are quoted inside strings and therefore not really comment markers.  I need to come up with a regex that only modifies `/*` if it is part of a quoted string.  I'll test some ideas and if anything looks solid, will commit the code.

**Comment by AlDanial** [comment]
Commit 471f130 has a regex that should correctly identify `/*` within strings (OK, they have to be single line strings) and outside of strings where they are treated as C/C++ comments.  Let me know if it works for you.

**Comment by filippucher1** [comment]
It works great, this solution, thanks.

Just a little problem - your commits 71bcf1caed2dfe506a389c196f44da5d95acf478 and 471f1304090408e1b99b807905b872ef065b9bf1 resolve problem for gradle files, but this Issue #140 concerns with Java files. Please insert regex command into Java block of commands too:
```perl
    'Java'               => [
#                               [ 'remove_matches'      , '^\s*//' ],
line to add ----->              [ 'remove_between_regex', '(["\']).*?/\*.*?\g1', '$' ],
                                [ 'call_regexp_common'  , 'C++'    ],
                                [ 'remove_inline'       , '//.*$'  ],
                            ],
```

Proposed java test file fragment:
```java
@Controller
@RequestMapping( "/path/*" )
public class ControllerClass {
/** 
* javadoc
* style
*/

/* block comment 1 - on one line */

/* 
  block comment 2
*/

/* 
* block comment 3
*/

// inline comment
```
Expected results:
```text
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Java                             1              4             12              3
-------------------------------------------------------------------------------
```

**Comment by AlDanial** [comment]
d'oh; OK the latest fix handles Java.  Thanks for the code example; I added it to `tests/inputs/Java.java` with an attribution to you.
The current fix is more sophisticated than earlier ones in that single line comments containing `/*` are split into two concatenated strings split between `/` and `*`.  In other words `@RequestMapping( "/path/*" )` becomes `@RequestMapping( "/path/" + "*")`.  This is useful so that if you run with `--strip-comments` the resulting output will still compile.
hmm, just tested this and see the output is missing the closing `)`.  This doesn't affect the comment count but the comment-stripped Java won't compile; will fix this next.
