### ISSUE TITLE
Diff error (quoted comments?)

### ISSUE THREAD

**Issue by kuh96** [AlDanial/cloc#15]
**Diff error (quoted comments?)** happens when I execute cloc --diff for diff-fail.c below.

```c
{/* begin */
{
     }
}/* end */
```

```txt
  perl modcloc-1.64.pl --v=1 --skip-uniqueness --diff diff-fail.c diff-fail.c >& diff-fail.log
```

where modcloc-1.64.pl is only for additional loggings:

```txt
diff cloc-1.64.pl modcloc-1.64.pl
8951a8952,8955
>
>       print "  ## $flag L=$n_L: [$line_L]\n";
>       print "  ## $flag R=$n_R: [$line_R]\n";
>
9033a9038
>                 die "diff failed !\n";
```

This error may happen **when the source file has a "code" + "comment" line followed by a "code" line, where these two "code" parts are exactly same.**

**Comment by kuh96** [comment]
[diff-fail.tar.gz | uploaded via ZenHub](https://files.zenhub.io/563316d9091eea220253de0f)

**Comment by AlDanial** [comment]
The root cause of the problem turns out to be how Algorithm::Diff's sdiff() function operates on these inputs.  When the first two braces start at the same column, the diff algorithm becomes confused on where to pair the L and R sets.  Rather than aligning line 1 to line 1, it aligns line 1 to line 2 and says the line 1 on the R file is new.

Here is a simple program to demonstrate the problem

    #!/usr/bin/env perl
    use strict;
    use warnings;
    use Algorithm::Diff qw ( sdiff );
    use Data::Dumper;

    my @lines_1 = (
            '{/* begin */',
            '{',
            '     }',
            '}/* end */',
        );
    my @lines_2 = (
            '{',
            '{',
            '     }',
            '}',
        );
    my @sdiffs = sdiff( \@lines_1, \@lines_2 );
    print Dumper(\@sdiffs);

The first output block shows '-' meaning "the line in the R file was deleted".  If you change the code so that there is a space after the second brace in @ lines_1, then the first output block shows 'c' which means the L and R lines have changed, not the R line has been deleted outright.

Short of writing a smarter sdiff() algorithm (a challenging task!), I'm not sure I have a solution.

**Comment by AlDanial** [comment]
If you rerun the diff test with the current master you'll get the correct output when diff'ing diff-fail.c.

The actual problem was self-induced:  commit 5bf6d81 took a new approach to stripping comments that was inconsistent with many other parts of cloc.  I reverted to the original with commit 9cd3e48.  Let me know if you still see incorrect --diff behavior.

**Comment by kuh96** [comment]
Thank you for comment.

I rerun the diff test with the current master (88f71e7), but the same error happened.

> The actual problem was self-induced: commit 5bf6d81 took a new approach ...

As I reported, this error already happens with version 1.64.
It seems that the regression introduced at commit 5bf6d81 does not matter.

**Comment by AlDanial** [comment]
The current development version of cloc gives this output for your original "diff-fail" case:

    $ cloc --skip-uniqueness --diff diff-fail.c diff-fail.c
           1 text file.
           1 text file.
           0 files ignored.                         

    2 errors:
    Diff error (quoted comments?):  diff-fail.c
    Diff error (quoted comments?):  diff-fail.c

    github.com/AlDanial/cloc v 1.67  T=0.01 s (86.2 files/s, 86.2 lines/s)
    -------------------------------------------------------------------------------
    Language                     files          blank        comment           code
    -------------------------------------------------------------------------------
    C
     same                            1              0              0              0
     modified                        0              0              0              0
     added                           0              0              0              0
     removed                         0              0              0              0
    -------------------------------------------------------------------------------
    SUM:
     same                            1              0              0              0
     modified                        0              0              0              0
     added                           0              0              0              0
     removed                         0              0              0              0
    -------------------------------------------------------------------------------


It still complains with "Diff error (quoted comments?):  diff-fail.c" but produces the correct output.
