### ISSUE TITLE
In-line comments remain when using --strip-comments

### ISSUE THREAD

**Issue by Inventitech** [AlDanial/cloc#153]
(Using v.1.72)

First, thanks for cloc. What an awesome tool!

I was recently using cloc's --strip-comments function, which writes out "a version of the file which has blank lines and comments removed." However, I noticed that in-line comments remain when using the --strip-comments. For example, 

```
when next_char == 'K' # Keep (special lookbehind that CAN be supported safely!)
```

is in the output of `cloc --strip-comments`

Having browsed cloc's reg-exp list, this seems to be the case for other languages than Ruby, too. Now, I understand why this is the case and that it is hard to efficiently remove in-line comments with reg-exen  (example: `assert_equal expected_data, actual_data, "Difference on #{dir} buildlogs!"`is not a comment even though it contains a `#` char).

However, I still think this behavior should 1. ideally be changed or 2. at least be documented for the time being, since it can confuse people who expect a file without comments -- which sloc does not produce.

**Comment by AlDanial** [comment]
Despite the merge if #154 I know it is still an irritant that inline comments aren't removed.  I actually implemented this about a year ago and but quickly saw broke a lot of logic stemming from the fact cloc views a line as either code or comment but not both (that is, a line with both code and comments is treated as code).  I'd have to implement a third category for "code and comment line" in order for the counts to come out right.  I'll close the issue since the documentation is at least correct now.

**Comment by Inventitech** [comment]
Great, thanks! :+1:
