### ISSUE TITLE
End of line continuation in custom language definition, am I using it correctly?

### ISSUE THREAD

**Issue by neilalex** [AlDanial/cloc#201]
Hi, 

I'm trying to create a custom language definition for Stata.

Everything seems to be working perfectly except for the end of line continuation -- in Stata it's three slashes ///. Regardless of how I try to code this, if I have a single line separated into two using these slashes, CLOC seems to count it as two distinct lines. I'm probably doing something wrong?

I've tried:

```
end_of_line_continuation ///
end_of_line_continuation \/\/\/
end_of_line_continuation \/\/\/$
end_of_line_continuation \/\/\/\s*$
```

plus a few other variants.

Using CLOC 1.72. Attaching my custom definition file as well as a sample Stata file (temp.do, zipped) that contains an example single line of code which CLOC is counting as two. I load the custom definition file using --read-lang-def.

Any ideas? Thanks in advance for the help!

Neil

[cloc_custom_definitions.txt](https://github.com/AlDanial/cloc/files/1106892/cloc_custom_definitions.txt)

[temp.zip](https://github.com/AlDanial/cloc/files/1106894/temp.zip)

**Comment by AlDanial** [comment]
Neil, I owe you an apology:  the end of line continuation stuff in cloc is currently a place-holder for what I'd planned as a future capability.  It does nothing right now.  My thinking on this capability changed over time and dampened my enthusiasm for it.  (I recall once writing an SQL query that spanned 8 lines.  I thought if I implemented the end of line continuation, this logic would count as just one line.)  Physical, rather than logical, lines of code seem to me to better quantify the amount of code.

In any case, I'll integrate your custom definitions into the core cloc code.

**Comment by neilalex** [comment]
Ah, okay, no problem -- good to know that's how it works. And I hear you on your philosophy towards this too.

Thanks for the super-prompt reply!

Neil
