### ISSUE TITLE
--diff Appears To Ignore Separate Files With Identical Changes

### ISSUE THREAD

**Issue by airbreather** [AlDanial/cloc#213]
Tested with 1.62 and 1.72, on Windows.

# Repro Steps
1. Create folders "00_BEFORE" and "01_AFTER" side-by-side
2. Create two files in "00_BEFORE" named "a.c" and "b.c", both just with:
```c
int main;
```
3. Create two files in "00_AFTER" also named "a.c" and "b.c", both just with:
```c
/* this is some kind of a comment */
int main;
```
4. Run CLOC as follows:
```
cloc --diff 00_BEFORE 01_AFTER --by-file-by-lang
```
5. Examine the console output.

## Expected
Two individual file entries, one for "a.c" and one for "b.c", each with one "same" line of code and one "added" line of comment, summing up to 2 "same" lines of code and 2 "added" lines of comments.

## Actual
Only one entry (it's always "b.c" for me).

**Comment by AlDanial** [comment]
This is expected behavior; see step 3 of https://github.com/AlDanial/cloc#How_it_works.
Before cloc does the diff, it excludes duplicate files.  If you'd rather have them included, run with ``--skip-uniqueness``:
<pre>
> cloc --skip-uniqueness --diff 00_BEFORE 01_AFTER --by-file-by-lang
       2 text files.
       2 text files.
       0 files ignored.                             

github.com/AlDanial/cloc v 1.73  T=0.02 s (62.3 files/s, 62.3 lines/s)
-------------------------------------------------------------------------------
File                           blank        comment           code
-------------------------------------------------------------------------------
00_BEFORE/b.c
 same                              0              0              1
 modified                          0              0              0
 added                             0              1              0
 removed                           0              0              0
00_BEFORE/a.c
 same                              0              0              1
 modified                          0              0              0
 added                             0              1              0
 removed                           0              0              0
-------------------------------------------------------------------------------
SUM:
 same                              0              0              2
 modified                          0              0              0
 added                             0              2              0
 removed                           0              0              0
-------------------------------------------------------------------------------
</pre>

(This actually brings up a new issue, namely that ``--by-file-by-lang`` only shows the by-file results.)
