### ISSUE TITLE
Parsing this 31-line, 180kb file takes 7 minutes on Core i7 @ 2.80GHz

### ISSUE THREAD

**Issue by antekone** [AlDanial/cloc#221]
I have a C# project that contains a file with some unit tests. I wanted to run `cloc` on this project, but it couldn't get past one file. I've extracted offending lines from this file and it appears that the `/*` pattern makes parsing very slow, even if `/*` appears inside some string. After removing `/*` from this file, parsing is quick again. But at the same time, removing long lines from the file makes the parsing quick again as well. But when both `/*` and long lines are present, the parsing is very slow.

Link to the file: http://anadoxin.org/Test.cs.gz

I didn't really dig into the problem, but maybe trimming very long lines could fix the issue?

File has 180kb because it contains long lines. It takes 421 bytes gzipped, because its contents is repeatitive.

```
$ time cloc .
       1 text file.
       1 unique file.                              
       0 files ignored.

github.com/AlDanial/cloc v 1.72  T=424.40 s (0.0 files/s, 0.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C#                               1              0              0             31
-------------------------------------------------------------------------------
cloc .  424,42s user 0,18s system 100% cpu 7:04,60 total
```

**Comment by AlDanial** [comment]
Using the development version of cloc on an Core i5 based Ubuntu 16.04 laptop I get
<pre>
> cloc Test.cs 
       1 text file.
       1 unique file.                              
       0 files ignored.

github.com/AlDanial/cloc v 1.73  T=0.01 s (109.9 files/s, 3405.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Smalltalk                        1              0              0             31
-------------------------------------------------------------------------------
</pre> 

which is a good news/bad news result I suppose.  Runs in a fraction of a second, but claims it is Smalltalk rather than C#.

The two languages share ``.cs`` as a file extension and the routine below attempts to figure out which is the right language based on the file's contents:
<pre>
10197 sub Csharp_or_Smalltalk {                    # {{{1
10198     my ($file        , # in
10199         $rh_Err      , # in   hash of error codes
10200         $raa_errors  , # out
10201        ) = @_;
10202 
10203     print "-> Csharp_or_Smalltalk($file)\n" if $opt_v > 2;
10204 
10205     my $lang = undef;
10206     my $IN = new IO::File $file, "r";
10207     if (!defined $IN) {
10208         push @{$raa_errors}, [$rh_Err->{'Unable to read'} , $file];
10209         return $lang;
10210     }
10211     my $cs_points        = 0;
10212     my $smalltalk_points = 0;
10213     while (<$IN>) {
10214         s{//.*?$}{};        # strip inline C# comments for better clarity
10215         next if /^\s*$/;
10216         if (/[;}{]\s*$/) {
10217             ++$cs_points       ;
10218         } elsif (/^(using|namespace)\s/) {
10219             $cs_points += 20;
10220         } elsif (/^\s*(public|private|new)\s/) {
10221             $cs_points += 20;
10222         } elsif (/^\s*\[assembly:/) {
10223             ++$cs_points       ;
10224         } else {
10225             ++$smalltalk_points;
10226         }
10227         if (/(\!|\]\.)\s*$/) {
10228             ++$smalltalk_points;
10229             --$cs_points       ;
10230         }
10231     }
10232     $IN->close;
10233     if ($smalltalk_points > $cs_points) {
10234         $lang = "Smalltalk";
10235     } else {
10236         $lang = "C#";
10237     }
10238     print "<- Csharp_or_Smalltalk($file)=$lang\n" if $opt_v > 2;
10239     return $lang;
10240 } # 1}}}
</pre>

If you can figure out a tweak that will get it to recognize your file as C#, let me know.

**Comment by antekone** [comment]
Sorry for late response.

I've managed to tweak this input file so that current master version of `cloc` properly detects it as C# (by adding lots of `};` lines), but I've noticed the issue is not there in the newest version.

I've also just runned newest devel version on the original codebase I was testing `cloc` on, and it went through without problems.

So I won't upload tweaked `Test.cs.gz` because it seems the issue is fixed in newest devel. Sorry for not checking this on the beginning.
