### ISSUE TITLE
Parsing spaces in parameters

### ISSUE THREAD

**Issue by rootd** [AlDanial/cloc#226]
On version 1.74, using spaces in parameters will lead to an error.

e.g:
```
cloc [...] --include-lang="C/C++ Header"

1 error:
Unable to read: Header
```

Same happens with spaces in the output path (`--out "..path with spaces.."`)

Host system: Windows 7 if that even matters

**Comment by AlDanial** [comment]
Try using single instead of double quotes perhaps?  On Linux, both work:
<pre>
> cloc --include-lang 'C/C++ Header' .
     333 text files.
     321 unique files.                                          
     334 files ignored.

github.com/AlDanial/cloc v 1.74  T=0.62 s (1.6 files/s, 2565.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C/C++ Header                     1            191            780            617
-------------------------------------------------------------------------------
> cloc --include-lang "C/C++ Header" .
     333 text files.
     321 unique files.                                          
     334 files ignored.

github.com/AlDanial/cloc v 1.74  T=0.61 s (1.6 files/s, 2595.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C/C++ Header                     1            191            780            617
-------------------------------------------------------------------------------
</pre>
(The above command is done on the cloc distribution.)

**Comment by rootd** [comment]
I already tried that, When using single quotes, the error message changed to
```
1 error:
Unable to read: Header'
```
I tried `--include-lang="C/C++ Header"` on version 1.72 and it works just fine. Single quotes also don't work on version 1.72, however that's because Windows bat requires double quotes in general.

**Comment by AlDanial** [comment]
I can't think of what could have changed between 1.72 and 1.74 to cause this change.  I did use a newer version of Strawberry Perl to compile the exe, and a 64 bit version of  Windows instead of 32.

Debugging this will be difficult for me because I don't own a Windows computer.  I have to set up an AWS instance which is kind of a drag; takes nearly an hour just to get Perl and the needed modules installed.

I believe you'd escape the space with a backslash rather than caret, perhaps give that a try.

**Comment by rootd** [comment]
Something must have changed the way parameters are passed to the perl script. I'm using the supplied .exe binary files. Maybe something at PAR::Packer changed?

**Comment by loolo78** [comment]
Any known workarounds? I downgraded to 1.72

**Comment by AlDanial** [comment]
I uploaded to the 1.74 release area, https://github.com/AlDanial/cloc/releases, a new executable that doesn't have this problem--at least in my testing.  It was created with a 32 bit Windows 7 Enterprise VirtualBox image downloaded from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ (the VirtualBox host is my Ubuntu 16.04 laptop).  On top of this VM I installed Strawberry Perl 5.26.1.1 (32 bit).  The name of the uploaded executable is cloc-1.74_x86.exe.

Please let me know if it resolves the issue for you.

**Comment by oltolm** [comment]
This issue still exists on Windows 10 64-bit with `cloc-1.74.exe`. But now I see that you have removed it from github. Is this bug the reason for it? `cloc-1.74_x86.exe` does not have this bug. BTW removing `cloc-1.74.exe` broke the scoop package.

```
cloc ..\djview-git\ --exclude-lang="Qt Linguist"
     127 text files.
     116 unique files.
      72 files ignored.

1 error:
Unable to read:  Linguist
```

**Comment by AlDanial** [comment]
Apologies on breaking the scoop package.  That's good to know for the future that removing files can cause problems for package managers.

Yes, I removed it because of this bug.  Seemed pointless to me to have two exe's when one caused problems.  Future Windows exe's will be made the same way I created the _x86.exe (on a 32 bit Windows 7 VM running on VirtualBox).
