### ISSUE TITLE
Reading other types of files?

### ISSUE THREAD

**Issue by basickarl** [AlDanial/cloc#266]
I'm wondering if there is a way to include the reading of non-programming files such as `.gitignore`, `.nvmrc`, `.eslintignore` files (and add these to the count)?

**Comment by AlDanial** [comment]
The most problematic of the ones you've listed is ``.gitignore`` which gets special treatment in cloc saying "ignore this file for sure" (ref ``%{$rh_Not_Code_Extension}`` in the cloc source).  The others are easier--simply define them as extensions for new languages.  You can then follow the steps at https://github.com/AlDanial/cloc#custom_lang to make your own definitions.

If you are working with the Perl source instead of a .exe, then you can just comment out or delete the offending line.
