### ISSUE TITLE
Config file with additional languages

### ISSUE THREAD

**Issue by fredefox** [AlDanial/cloc#268]
Would it be possible to get a config file that `cloc` would look for languages in?

I know I can use `--read-lang-def` to manually point `cloc` to the location of such a file, but this is cumbersome when usually you want `cloc` to remember your custom (weirdly specific) language.

My current workaround is this:

```
$ which cloc  
cloc: aliased to cloc --read-lang-def=$HOME/.config/cloc/langs
```

**Comment by fredefox** [comment]
Also it would be nice if you could add Agda:

```
$ cat ~/.config/cloc/langs
Agda
    filter remove_haskell_comments >filename<
    extension agda
    extension lagda
    3rd_gen_scale 2.11
```

**Comment by AlDanial** [comment]
I've had the idea of a config file (nominally "``.clocrc``") in the back of my mind for a few years actually.

I will postpone implementing that for a bit longer though, since I hope to find time to release the current development version as v1.76 this Friday.  I'll commit to the config file in v1.78.

**Comment by fredefox** [comment]
The location of said file is not important to me. Just wanted to point out that `$HOME/.config/appname/*` is also a valid location for config files according to the [xdg-spec].

[xdg-spec]: https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
