### ISSUE TITLE
Out of memory error?

### ISSUE THREAD

**Issue by mr2001** [AlDanial/cloc#279]
Hello,

I ran the following script. After approx 6 hours, it ended with an error message:

**"D:\LOC\cloc-1.76.exe" --diff "Folder1" "Folder2" --diff-timeout 3000 --match-d="/(SMC_Ap
ps)/" --out=out.txt
    1793 text files.
    1793 text files.s
Out of memory!nique files.**

There are approx 16,000 files in Folder1 and also approx 16,000 in Folder2
There are also some very long and unusual file and directory names in "SMC_Apps" folder, like:
**CommonServiceLocator.1.0.nupkg.52a6a757975a4df0a9b32bd2aea87f30**
**~sak766e0efd01d1b6a0.tmp.1fbfebdb26d9449aa06b2b8940ed9a86**
(extension is **.fbfebdb26d9449aa06b2b8940ed9a86** in this case)

Please advise.

**Comment by AlDanial** [comment]
Rerun with ``--diff-alignment=compared_files.txt`` to see how cloc is aligning the 1793 files in the two folders.  Then separate the contents of the folders into smaller sets so that you are only running maybe 500 files at a time.  (The file ``compared_files.txt`` will tell you which of the 16,000 files are understood as source code.)

Don't worry about the unusual files with weird extensions.  They will be ignored.

**Comment by mr2001** [comment]
I narrowed down the error, please see the new Issue I created

**Comment by AlDanial** [comment]
Closed per #280 and commit fff9d47
