### ISSUE TITLE
DTSX files

### ISSUE THREAD

**Issue by cccycling** [AlDanial/cloc#281]
Can you please include DTSX files just count the XML of the file? It is built with a tool that results in most of the XML and your code for every script task is stored in that as well.  Allow us to override and just count it as a text file.

**Comment by mr2001** [comment]
Thank you for your email AlDanial but it is not clear to me what I can do in order to avoid this error? I have no control over the folder's contents, DTSX files, etc. they come from other departments in our company and there are thousand of files for some projects and maybe hundreds of coders.
I need a way to modify the script in order to avoid this timeout error. Please advise.

Regards,
M.R.
________________________________

**Comment by AlDanial** [comment]
https://github.com/AlDanial/cloc#AdditionalLanguages explains what I need to support a new file type.

**Comment by AlDanial** [comment]
no response
