### ISSUE TITLE
--follow-links breaks --not-match-d

### ISSUE THREAD

**Issue by csmouse** [AlDanial/cloc#286]
**CLOC 1.76**
steps to reproduce on ubuntu 16.04.4

```
$ mkdir -p project/subdir
$ echo 'print "hello"' > project/subdir/test.py
$ cloc --not-match-d subdir project
       0 text files.
       0 unique files.
       1 file ignored.
$ cloc --follow-links --not-match-d subdir project
       1 text file.
       1 unique file.
       0 files ignored.

github.com/AlDanial/cloc v 1.76  T=0.05 s (19.5 files/s, 19.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           1              0              0              1
-------------------------------------------------------------------------------
```

I would expect the file under the `subdir` directory to be ignored in both of the above invocations of `cloc`. Does my regex need to change somehow if I'm using `--follow-links`?

**Comment by AlDanial** [comment]
Your regex is fine--the code was in error.

This issue was interesting for a couple of reasons:  first it was educational in that, while documented, I didn't realize the ``find()`` subroutine in the ``File::Find`` module skips the file preprocessor (where I apply ``--not-match-d``) if it is told to follow links.  To fix this I had to write a separate preprocessor that is called when given ``--follow-links``.  Second, while testing the new code I realized the existing code had a bug in how ``--fullpath`` and ``--not-match-d`` interacted.  Had to write six new test cases to cover everything.

I'd appreciate it if you could pull the dev code and test this fix for a while before I close out the issue

**Comment by csmouse** [comment]
Thanks for the fast response. I verified `dev` with my full test case, and it works great.
