### ISSUE TITLE
Some C# LOCs are counted under Small talk

### ISSUE THREAD

**Issue by vikramlagu** [AlDanial/cloc#309]
I am observing a behaviour where-in some of the c# files are counted as small talk files.  One of those files has 1000 line of code which is commented from start to end. Is this a known issue? What is the workaround/fix for this.

**Comment by AlDanial** [comment]
The most direct work-around is ``cloc --force-lang="C#,cs"`` to force all ``.cs`` files to be counted as C#.

The a better fix would be to test commenting out a portion of the subroutine which might be favoring Smalltalk over C#.  Currently it is
<pre>
11213 sub Csharp_or_Smalltalk {                    # {{{1
11214     my ($file        , # in
11215         $rh_Err      , # in   hash of error codes
11216         $raa_errors  , # out
11217        ) = @_;
11218 
11219     print "-> Csharp_or_Smalltalk($file)\n" if $opt_v > 2;
11220 
11221     my $lang = undef;
11222     my $IN = new IO::File $file, "r";
11223     if (!defined $IN) {
11224         push @{$raa_errors}, [$rh_Err->{'Unable to read'} , $file];
11225         return $lang;
11226     }
11227     my $cs_points        = 0;
11228     my $smalltalk_points = 0;
11229     while (<$IN>) {
11230         s{//.*?$}{};        # strip inline C# comments for better clarity
11231         next if /^\s*$/;
11232         if (/[;}{]\s*$/) {
11233             ++$cs_points       ;
11234         } elsif (/^(using|namespace)\s/) {
11235             $cs_points += 20;
11236         } elsif (/^\s*(public|private|new)\s/) {
11237             $cs_points += 20;
11238         } elsif (/^\s*\[assembly:/) {
11239             ++$cs_points       ;
11240         } else {
11241             ++$smalltalk_points;
11242         }
11243         if (/(\!|\]\.)\s*$/) {
11244             ++$smalltalk_points;
11245             --$cs_points       ;
11246         }
11247     }
11248     $IN->close;
11249     if ($smalltalk_points > $cs_points) {
11250         $lang = "Smalltalk";
11251     } else {
11252         $lang = "C#";
11253     }
11254     print "<- Csharp_or_Smalltalk($file)=$lang\n" if $opt_v > 2;
11255     return $lang;
11256 } # 1}}}
</pre>

I believe line 11241 is giving too much credit for Smalltalk so try commenting these out by prefixing with ``#``:
<pre>
11240 #        } else {
11241 #             ++$smalltalk_points;
</pre>

If you could give me your C# files for closer study I'll know for sure.

btw, your line numbers will likely differ since I'm looking at the development code on the git HEAD.

**Comment by vikramlagu** [comment]
thanks for the response. I think the force option would work in our case since we only have this problem with two files.  

I have a similar problem wherein our .ASPX pages contain HTML / javascript / vb ( serverside ) code.  The tool counts everything as ASPX. I am assuming the line count considers different languages that ASPX file can contain.  Can you confirm this?   Secondly,  Is there a switch that I can use to count these lines separately for each language?

**Comment by AlDanial** [comment]
I pushed a fix that should count your code correctly without need of ``--force-lang``.

Regarding .ASPX with HTML, JavaScript, and Visual Basic--cloc is not designed to understand embedded languages.  This is a fundamental limitation of the tool.  I will note this in the documentation.
