### ISSUE TITLE
How to exclude subdir

### ISSUE THREAD

**Issue by luanjampa** [AlDanial/cloc#31]
Hello, how I exclude sub dir, example: src/test, src/docs. Thanks

**Comment by AlDanial** [comment]
See the section "Filter Options" at https://github.com/AlDanial/cloc#options

**Comment by luanjampa** [comment]
@AlDanial works when used --exclude-dir=test 
But if try --excludir-dir=src/test not works :\

another question, if exist another directory called 'test', exemple:
spec/test.
When I execute cloc with "--exclude-dir=test " both directory(src/test,spec/test) are excluded?

**Comment by AlDanial** [comment]
If you say --exclude-dir=test then both src/test and spec/test are excluded.

There isn't (yet) a way to prune directories based on anything except the last directory name in a path.

**Comment by jolkdarr** [comment]
```cloc``` should deny invocations with option ```--excludir-dir``` containing separators like ```src/test``` because the user might think the directory has been successfully filtered.

**Comment by luanjampa** [comment]
thanks for answer @AlDanial, and I think this would be a great feature.

indeed @jolkdarr

**Comment by AlDanial** [comment]
Good idea @jolkdarr.  I'll add a warning if --exclude-dir and --not-match-d contain separators.

**Comment by IncludeSec** [comment]
Any chance of getting exclude dir or another option for excluding a path. For instance if I have a dir name test/foo/bar/lala and test/bar/foo/momo I want to only exclude test/bar/* but NOT test/foo/bar/

I don't think there is a way to do that currently in cloc short of xargs/find magic feeding a file list into cloc.

**Comment by AlDanial** [comment]
Yes, this is definitely on my to-do plan.

I actually took a shot at implementing the solution--I figured it would be a piece of cake--but it was a bit more involved than I first thought.  Until last week my focus was getting v1.66 checked out solidly enough to release.  Now that it is out I will turn my attention back to the harder problems.

**Comment by AlDanial** [comment]
OK, so maybe the solution was easy after all.  Internally, the problem came down to <code>--not-match-d</code> only examining the last directory in the path, ie, for <code>/usr/local/lib</code>, cloc would only test <code>--not-match-d</code>'s regex against <code>lib</code>.  Git commit 242c795 expands the <code>--fullpath</code> switch so that it also updates <code>--not-match-d</code>'s behavior to consider the full path.

With the new code you should be able to achieve what you're after.  Here's an example session:

<pre>
mkdir -p test/foo/bar/lala test/bar/foo/momo
echo "echo hi"    > test/foo/bar/lala/tfbl.sh
echo "echo hello" > test/bar/foo/momo/tbfm.sh

# run 1: count everything
cloc --by-file test

       2 text files.
       2 unique files.                              
       0 files ignored.

github.com/AlDanial/cloc v 1.67  T=0.01 s (140.6 files/s, 140.6 lines/s)
---------------------------------------------------------------------------------------
File                                     blank        comment           code
---------------------------------------------------------------------------------------
test/bar/foo/momo/tbfm.sh                    0              0              1
test/foo/bar/lala/tfbl.sh                    0              0              1
---------------------------------------------------------------------------------------
SUM:                                         0              0              2
---------------------------------------------------------------------------------------

# run 2: only exclude test/bar/* but not test/foo/bar/
cloc --by-file --fullpath --not-match-d test/bar test

       1 text file.
       1 unique file.                              
       1 file ignored.

github.com/AlDanial/cloc v 1.67  T=0.01 s (89.8 files/s, 89.8 lines/s)
---------------------------------------------------------------------------------------
File                                     blank        comment           code
---------------------------------------------------------------------------------------
test/foo/bar/lala/tfbl.sh                    0              0              1
---------------------------------------------------------------------------------------

# run 3: only exclude test/foo/bar but not test/bar/
cloc --by-file --fullpath --not-match-d test/foo/bar test

       1 text file.
       1 unique file.                              
       1 file ignored.

github.com/AlDanial/cloc v 1.67  T=0.01 s (80.6 files/s, 80.6 lines/s)
---------------------------------------------------------------------------------------
File                                     blank        comment           code
---------------------------------------------------------------------------------------
test/bar/foo/momo/tbfm.sh                    0              0              1
---------------------------------------------------------------------------------------

</pre>

One last thing remains before I can close this out:  give the same treatment to <code>--exclude-dir</code>.

**Comment by AlDanial** [comment]
Actually, <code>--exclude-dir</code> serves a slightly different purpose.  I left its behavior alone and implemented @jolkdarr's suggestion to prohibit path separators in <code>--exclude-dir</code>.
