### ISSUE TITLE
Running cloc in single repo vs root folder

### ISSUE THREAD

**Issue by Hariom-Algo** [AlDanial/cloc#311]
I have root folder which has all the repo .
When I run cloc in whole folder I am getting the below result 
files | language | blank | comment | code
1090 | JSON | 161 | 0 | 507023

where as if I run cloc individually in each repo and then combine

files | language | blank | comment | code
 1104 | JSON|161 | 0 | 507769

Why there is difference in file no .
What is advisable to run in each repo and then combine or run again root(collection of all repo)

**Comment by AlDanial** [comment]
My guess as to why the whole folder counted fewer files than the individual repos is because some of the JSON files are duplicated between the repos.  cloc will check for duplicate files and only count one instance of each.  To disable this feature, rerun on the whole folder using ``--skip-uniqueness``.

**Comment by Hariom-Algo** [comment]
It worked as suggested
