### ISSUE TITLE
Write and Force-lang-def don't work for C#

### ISSUE THREAD

**Issue by KingKadelfek** [AlDanial/cloc#319]
I was doing very basic tests with filters, but a simple --write-lang-def and --force-lang-def seems to cause C# stats to no longer being detected.
With the following command:
`cloc "my_folder"`
Everything is fine, C#, XML and such files stats are displayed.

Then I type:
```
cloc --write-lang-def="filter.txt" "my_folder"
cloc --force-lang-def="filter.txt" "my_folder"
```
And C# stats no longer appear.
Here is a screenshot of the whole process (I didn't change anything in any file between those commands):
[https://i.imgur.com/ftuuUra.png](https://i.imgur.com/ftuuUra.png)

**Comment by AlDanial** [comment]
C#--and a dozen other languages--are tricky because they share file extensions with other languages.  In the case of C# it is Smalltalk which also uses ``.cs``.  These languages have hard-coded subroutines in cloc that try to figure out which language filter to use.  There is currently no provision to include this information in the output of ``--write-lang-def``.

There are a couple of work-arounds.  If you use ``--read-lang-def`` instead of ``--force-lang-def``, then cloc will count your C# files as usual.  The difference is ``..read..`` uses internal definitions where ever possible and only uses file definitions where there are no corresponding internal definitions.  ``..force..`` will always use what's in the file.

The second work-around is to use the new switch I just added, ``--write-lang-def-incl-dup``, which will include the duplicated file extensions in the language definition file.  This causes new problems, however, since cloc will not use such a file until the duplicates are taken out.
