### ISSUE TITLE
how can i count other language like .wxml file?

### ISSUE THREAD

**Issue by lijicheng123** [AlDanial/cloc#355]
i want to count the code of wechat miniprogram which include many .wxml and .wxss and .wxs file,
is there any way i can use

**Comment by AlDanial** [comment]
I'm not familiar with .wxml and .wxss files.  How are comments defined?  Can you point me to a wechat application with such files?  .wxs is currently associated with WiX.

**Comment by lijicheng123** [comment]
maybe you can read wechat's miniprogram official document 

[https://developers.weixin.qq.com/miniprogram/en/dev/](https://developers.weixin.qq.com/miniprogram/en/dev/)

thanks

**Comment by AlDanial** [comment]
The documentation by itself is only half the issue.  I'll need sample inputs to test the solution on and there's no obvious source for that.  I'll leave the testing to you.  You can implement counters for wechat by working with a custom language definition file. The steps are:
1. save cloc's existing language definitions to a file with
``cloc --write-lang-def=all_lang_def.txt``
2. edit ``all_lang_def.txt`` and modify the extension for the existing "WiX Source" entry from ``wxs`` to something like ``wwwxs`` so that it doesn't conflict with the wechat ``wxs`` files.  It should be around line 1479:
<pre>
1476 WiX source
1477     filter remove_html_comments
1478     filter call_regexp_common HTML
1479     extension wxs
1480     3rd_gen_scale 1.90
</pre>
3. add these wechat definitions to the end of the ``all_lang_def.txt`` file:
<pre>
WeChat WXML
    filter remove_html_comments
    filter call_regexp_common HTML
    extension wxml
    3rd_gen_scale 1.90
WeChat WXS
    filter remove_html_comments
    filter call_regexp_common HTML
    filter rm_comments_in_strings " /* */
    filter rm_comments_in_strings " //
    filter call_regexp_common C
    extension wxs
    3rd_gen_scale 1.00
WeChat WXSS
    filter rm_comments_in_strings " /* */
    filter rm_comments_in_strings " //
    filter call_regexp_common C
    extension wxss
    3rd_gen_scale 1.00
</pre>
4. run cloc using this language definition file
``cloc --force-lang-def all_lang_def.txt``   _your input files/dirs_

**Comment by spencerwooo** [comment]
@AlDanial So will `cloc` plan on supporting `.wxml` and `.wxss`? They basically have the same grammar as regular HTML and CSS. (Official documents are available here: [WXML](https://developers.weixin.qq.com/miniprogram/en/dev/reference/wxml/), [WXSS](https://developers.weixin.qq.com/miniprogram/en/dev/reference/wxs/))
