### ISSUE TITLE
[Question] Way to use cloc to distinguish between code and comments

### ISSUE THREAD

**Issue by mensfeld** [AlDanial/cloc#377]
Is there a way to use `cloc` to figure out the distribution of the comments and code in files? Cloc seems to have a pretty decent qualifiers for distinguishing between code and comments nad I wanted to use them to get something similar to that:

`file.rb`:

```ruby
# This is a comment
# Second line of comments

def sum(a, b)
  a + b
end
```

`cloc -with-magical-commands-or-a-patched-cloc`

results:

```
file.rb:
1. Comment
2. Comment
3. Blank
4. Code
5. Code
6. code
```

That is, I'm interested in exact positions in files of lines of code and comments (which one is what).

Thank you in advance.

**Comment by AlDanial** [comment]
There _is_ a way to get what you're after, but perhaps not in a format suitable to you.  If you use the undocumented switch ``--html``, cloc will create an HTML file for each input file with color-coded and code and comment lines.  If you open the HTML file in a browser you'd see something like this

<pre>
&nbsp; <span class="clinenum"> 1 </span> &nbsp;<span class="comment"># This is a comment</span> &nbsp;
&nbsp; <span class="clinenum"> 2 </span> &nbsp;<span class="comment"># Second line of comments</span> &nbsp;

&nbsp; <span class="linenum"> 1 </span> &nbsp;<span class="normal">def sum(a, b)</span> &nbsp;
&nbsp; <span class="linenum"> 2 </span> &nbsp;<span class="normal">  a + b</span> &nbsp;
&nbsp; <span class="linenum"> 3 </span> &nbsp;<span class="normal">end</span> &nbsp;
</pre>

In theory you could write a script to parse out the comment and code line number identifiers, as well as blank lines.

The ``--html`` switch is deliberately undocumented because I've never gotten the output to appear the way I've wanted, and have lost interest in getting it right.

**Comment by mensfeld** [comment]
It almost suits my needs apart from the counting that resets but I can work with that as I can easily count lines myself. Thank you! That is an amazing news :)

**Comment by mensfeld** [comment]
One more follow up question @AlDanial: is there a way to point out a dir where I could store all the resulting files? The chance of mismatch with the analyzed files would be lower. Something like:

'cloc --html --output-path ./somewhere'

**Comment by mensfeld** [comment]
Update: no need anymore. Everything works faster and better than I expected. Thank you!
