### ISSUE TITLE
Negative values?

### ISSUE THREAD

**Issue by globalblob** [AlDanial/cloc#380]
This may or may not be a bug. Upon trying cloc on our system, I've noticed the lines of Prolog comments were counted as '-2'. I have searched through the main help page and could not find anything that would indicate a special meaning of negative numbers.
```

github.com/AlDanial/cloc v 1.80  T=20.89 s (28.7 files/s, 342898.5 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
Perl                            291          13227        7045981          48377
Bourne Shell                     17           1588           2126          13316
Python                          129           3741           7227          10727
XML                              82              1              3           5756
XSLT                             10            181             39           3276
C                                21            200            625           1473
JSON                             26             11              0           1434
XSD                               8            103             56           1213
make                              6            233             97            565
IDL                               3            178            149            493
Prolog                            2             87             -2            258
HTML                              1             10              8             71
C/C++ Header                      1             10              0             24
YAML                              1              0              0             19
Bourne Again Shell                1              8              9             19
C Shell                           1              0              0              4
--------------------------------------------------------------------------------
SUM:                            600          19578        7056318          87025
--------------------------------------------------------------------------------
```

**Comment by AlDanial** [comment]
Definitely a bug!  Please identify which of the two Prolog files (or maybe both) cause the negative value.  If you don't already know which files were identified as Prolog, do this to see them:
<pre>
cloc --csv --by-file  YOUR_CODE_HERE | grep Prolog
</pre>
Then, if the file isn't propietary, please attach it so that I can see what's going on.

**Comment by globalblob** [comment]
Thanks. Found the offending files - they are in fact in Perl, not it Prolog. Let's see if I can attach one of them to the thread. 

[case1.txt](https://github.com/AlDanial/cloc/files/3018211/case1.txt)

**Comment by globalblob** [comment]
Another unrelated issue. It seems cloc counts everything in the '__DATA__' section of Perl files towards lines of comments (https://stackoverflow.com/questions/13463509/the-data-syntax-in-perl). I think this section is typically used to embed files into the code and we use it to embed test case inputs. The final statics from cloc for our system looks a bit funny - 100,000 lines of code and 7,000,000 lines of comments :) Please let me know you'd like me to create a separate issue.

**Comment by AlDanial** [comment]
Re: case1.txt, yes, I'm able to duplicate the problem.  Crazy stuff going on--the comment remover actually ends up adding a comment (repeats the ``#!`` line), never seen this before.  Also it's a good case to sharpen the Prolog v. Perl identifier.

I've got a few things going on so it may be a week or so before I push the fix.

Re: ``__DATA__``, my uses of it also include files, but my files contain numeric and text data, nothing to do with code.  I'm reluctant to change the current behavior because I think my use case is more common than yours.

In any event, so long as you're working with the Perl source version as opposed to the Windows executable, it is easy to customize your version of cloc to count the ``__DATA__`` section as code.
Just remove the first entry in Perl's language filters starting at line 7852 (in the git master, line positions in v1.80 will be a bit different); in other words replace
<pre>
 7852     'Perl'               => [   [ 'remove_below'        , '^__(END|DATA)__'],
 7853                                 [ 'remove_matches'      , '^\s*#'  ],
 7854                                 [ 'remove_below_above'  , '^=head1', '^=cut'  ],
 7855                                 [ 'remove_inline'       , '#.*$'   ],
 7856                             ],
</pre>
with
<pre>
 7852     'Perl'               => [ 
 7853                                 [ 'remove_matches'      , '^\s*#'  ],
 7854                                 [ 'remove_below_above'  , '^=head1', '^=cut'  ],
 7855                                 [ 'remove_inline'       , '#.*$'   ],
 7856                             ],
</pre>
Alternatively you could do the same with a custom language definition, ref https://github.com/AlDanial/cloc#create-custom-language-definitions-

**Comment by AlDanial** [comment]
Turned out just making the Perl v. Prolog logic smarter solved the problem.  (I do wonder though if there's a legitimate Prolog file out there that will generate a negative count.)

**Comment by globalblob** [comment]
Thanks, will give it a try!
