### ISSUE TITLE
Lines not being identified Properly

### ISSUE THREAD

**Issue by asadcr** [AlDanial/cloc#381]
Please see `SampleFile.Java` https://drive.google.com/file/d/1bVktc0EfApvTLwKxwQbMHUKHOEfwhMkn/view?usp=sharing

The lines are being identified as `Blank= 4` `Comment=7` `Code=150`
However the actual numbers are `Blank= 6` `Comment=3` `Code=152`

See Similar Case in C++ https://drive.google.com/open?id=1fcdmLDvnJQV_mveOjf6WPGpN67j09JLj

The lines are being identified as `Blank= 27` `Comment=105` `Code=36`
However the actual numbers are `Blank= 27` `Comment=1` `Code=140`

using ` --strip-str-comments` still doesn't count properly and produces  `Blank= 27` `Comment=0` `Code=141` which wrong

**Comment by AlDanial** [comment]
I confirmed the problems, however, it will be several weeks before I have time to find solutions.

**Comment by AlDanial** [comment]
The Java file turned out to trigger a bug in the Regexp::Common module but I have a work-around.  The C file is harder; cloc is getting confused by strings like
<pre>"\"]/pre_triggers/*"</pre>
as it thinks the trailing ``/*`` starts a comment.  I have code that attempts to strip comment markers within strings but _that_ is getting confused by the ``\"`` ; cloc sees just the first three characters, ``"\"``, as a string then thinks the ``/*`` is outside a string and therefore a real comment marker.  Pretty nuts!  I'll have to make the string identification logic smarter.

**Comment by AlDanial** [comment]
Have the C counter working properly now, but you'll need to use the ``--strip-str-comments`` switch, ie,
<pre>
> cloc --strip-str-comments SampleFile.c
       1 text file.
       1 unique file.                              
       0 files ignored.

github.com/AlDanial/cloc v 1.81  T=0.01 s (128.3 files/s, 21554.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C                                1             27              1            140
-------------------------------------------------------------------------------
</pre>

There's additional information on ``--strip-str-comments``at https://github.com/AlDanial/cloc#limitations-

**Comment by asadcr** [comment]
are we expecting any release sooner ? or should I build latest development for now ?

**Comment by AlDanial** [comment]
I'm aiming for a release within the next four weeks.
