### ISSUE TITLE
Unknown option: by_percent

### ISSUE THREAD

**Issue by samhavens** [AlDanial/cloc#40]
Maybe I am missing something, but I can't get the by-percent option to work at all, I just get the same message every time, "Unknown option: by_percent".

**Comment by AlDanial** [comment]
That's odd, works for me.  Note that <code>--by-percent</code> takes an argument that defines how the denominator in the percentage is computed.  Here's output I get when I count lines of cloc itself using code count as the denominator:

<pre>
ubuntu> cloc --by-percent c cloc
       1 text file.
       1 unique file.                              
       0 files ignored.

https://github.com/AlDanial/cloc v 1.65  T=0.07 s (13.7 files/s, 147685.2 lines/s)
-------------------------------------------------------------------------------
Language                     files        blank %      comment %           code
-------------------------------------------------------------------------------
Perl                             1           8.14          12.90           8891
-------------------------------------------------------------------------------
</pre>

What happens when you run<pre>cloc --by-percent c cloc</pre> ?

**Comment by samhavens** [comment]
Hi, sorry for the delay. I just had a kid, things are crazy :) Here's the output:

sam@sam-VirtualBox ~ $ cloc --by-percent c cloc
Unknown option: by-percent

**Comment by AlDanial** [comment]
hey, that's great!  The sleep deprivation in the early year(s) is a real drag though.

Anyway, I have a theory on what's going on:  the cloc command you're invoking may not be the one you downloaded.  What do you get for 

  cloc --version

?  If it isn't 1.65, then you aren't running a version that has the feature.  You can download the source to a local directory then run

 ./cloc --version

and you should see the latest.

**Comment by samhavens** [comment]
thanks! It was versioning...
