### ISSUE TITLE
Why I add some annotations at the end of python files, the lines of code is different? 

### ISSUE THREAD

**Issue by yanlongbinluck** [AlDanial/cloc#405]
Hi, thanks for your great repo.
When I add some annotations to the python file below:
[https://github.com/ultralytics/yolov3/blob/master/utils/utils.py](url)

without annotation:
```
github.com/AlDanial/cloc v 1.74  T=0.01 s (150.7 files/s, 112402.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           1            145            136            465
-------------------------------------------------------------------------------
```
with annotation at the end of utils.py:
```
    '''
    hello
    '''

```
```
github.com/AlDanial/cloc v 1.74  T=0.01 s (151.8 files/s, 113708.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           1            145            305            299
```
why? I only add 3 lines of annotations.

**Comment by AlDanial** [comment]
That's a pretty nasty bug you hit upon.  The explanation is simple, but the solution may or may not be what you want.

Simple solution:  upgrade to a newer version of cloc and use the ``--docstring-as-code`` switch.  The counts will come out like this:

<pre>
github.com/AlDanial/cloc v 1.83  T=0.01 s (90.4 files/s, 67346.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           1            144            116            485
-------------------------------------------------------------------------------
</pre>

<pre>
github.com/AlDanial/cloc v 1.83  T=0.01 s (94.5 files/s, 70659.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           1            144            116            488
-------------------------------------------------------------------------------
</pre>

Then again, if you want docstrings to be counted as comments instead of code, this solution won't be of interest to you.

As to the explanation:  by default, cloc treats Python docstrings as comments.  To remove the comments as part of the code count it first replaces triple quotes with C-style comment markers,
``/*`` and ``*/``, then calls the Parse::Regexp::Common module to identify and remove the C comments.  That's where the trouble lies.  ``utils.py`` has two instances of ``glob.glob('%s/*.*' % path)`` which contain ``/*`` and therefore appear like start-of-C comment markers.  The extra docstring at the end of the file throws it for a loop in trying to pair up the C comments.

This is a problem that has troubled cloc for a long time and I have yet to devise a robust solution.

There's also a work-around on your end which is to separate the ``/`` and ``*`` characters in the glob with, for example, ``glob.glob('%s/' + '*.*' % path)`` (but I would agree with you if you said it is crazy to change code to acomodate a line counter!).

**Comment by yanlongbinluck** [comment]
I see. thank you~

**Comment by AlDanial** [comment]
I just realized there's a clean fix for this problem in Python (and any other language that does not recognize C comments):  add a step to first take out all these characters before continuing with the other steps.
I'll implement the fix this weekend.

**Comment by yanlongbinluck** [comment]
@AlDanial ,Hi, sorry, I am new to linux, I want to know how to install latest version of cloc?
my system is ubuntu, when I `sudo apt-get install cloc`, I only can install version1.74. It shows this is latest version.
is need to install from source code? and how to do it?
thank you very much!

**Comment by AlDanial** [comment]
It is pretty simple: go to the Releases page, https://github.com/AlDanial/cloc/releases, and download the source version, eg cloc-1.82.pl (https://github.com/AlDanial/cloc/releases/download/1.82/cloc-1.82.pl).

After you've downloaded the file, make it executable if it isn't already with ``chmod u+x cloc-1.82.pl``.  You can relocate it to any directory on your ``$PATH``, or just run it in place with ``./cloc-1.82.pl ..your stuff..``

Alternatively, pull down the latest development version by downloading from the Raw link at https://github.com/AlDanial/cloc/blob/master/cloc

**Comment by yanlongbinluck** [comment]
I made it, thank you.

**Comment by AlDanial** [comment]
The development branch, https://github.com/AlDanial/cloc/blob/master/cloc, now has a clean fix for this problem.  No need to edit your code, and works with and without ``--docstring-as-code``.

Thanks for reporting the issue.
