### ISSUE TITLE
Smarty detection not working, unless forced

### ISSUE THREAD

**Issue by apcro** [AlDanial/cloc#411]
Using `cloc 1.82`, Smarty `.tpl` files are ignored unless `--force-lang` is used.

Examples, using the same folder (which contains 300+ `.tpl` files)

```
cloc {path}
     304 text files.
     303 unique files.                                          
     305 files ignored.

github.com/AlDanial/cloc v 1.82  T=0.16 s (12.3 files/s, 797.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Smarty                           1              2              2             96
HTML                             1              2              0             28
-------------------------------------------------------------------------------
SUM:                             2              4              2            124
-------------------------------------------------------------------------------
```

```
cloc --force-lang="Smarty",tpl {path}
     304 text files.
     303 unique files.                                          
       4 files ignored.

github.com/AlDanial/cloc v 1.82  T=0.39 s (780.4 files/s, 111330.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Smarty                         302           4559            943          37696
HTML                             1              2              0             28
-------------------------------------------------------------------------------
SUM:                           303           4561            943          37724
-------------------------------------------------------------------------------
```
The path in question does contain 1 HTML file, all other files (including the 4 ignored files), end in `.tpl`

**Comment by AlDanial** [comment]
I'd received complaints that cloc was falsely identifying non-Smarty ``.tpl`` files--evidently this extension identifies templates for other languages and applications--as being Smarty so I added these lines:

<pre>
 5307             } elsif ($Language_by_Extension{$extension} eq 'Smarty') {
 5308                 if ($extension ne "tpl") {
 5309                     # unambiguous -- if ends with .smarty, is Smarty
 5310                     return $Language_by_Extension{$extension};
 5311                 }
 5312                 # Smarty extension .tpl is generic; make sure the
 5313                 # file at least roughly resembles PHP.  Alternatively,
 5314                 # if the user forces the issue, do the count.
 5315                 my $force_smarty = 0;
 5316                 foreach (@opt_force_lang) {
 5317                     if (lc($_) eq "smarty,tpl") {
 5318                         $force_smarty = 1;
 5319                         last;
 5320                     }
 5321                 }
 5322                 if (really_is_php($full_file) or $force_smarty) {
 5323                     return 'Smarty';
 5324                 } else {
 5325                     return $language; # (unknown)
 5326                 }
</pre>

which, in your case, go too far the other way in ignoring legitimate Smarty files.  I believe the culprit is ``really_is_php()`` which ought to be replaced by a call to a more intelligent decision maker.

If you can point me to a corpus of Smarty files to test new logic on, that would be helpful.  I'm guessing you can't tar up your 37,696 files and post that?

**Comment by AlDanial** [comment]
I replaced ``really_is_php()`` with a new subroutine, ``really_is_smarty()``, which sums points each time it sees a ``.tpl`` file with a line containing one of these patterns
<pre>
{if
{include
{*
*}
{/if}
{$\w
</pre>

Two or more points will label the file as Smarty.  Let me know if this is sufficiently accurate on your body of files.

**Comment by apcro** [comment]
I've tried the new version on the same set of files (count is different as this is a site in active development)

```
cloc {path} 
     313 text files.
     312 unique files.                                          
     107 files ignored.

github.com/AlDanial/cloc v 1.83  T=0.24 s (855.2 files/s, 144907.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Smarty                         208           3692            907          30785
HTML                             1              2              0             28
-------------------------------------------------------------------------------
SUM:                           209           3694            907          30813
-------------------------------------------------------------------------------
```

With `--force-lang`

```
cloc --force-lang="Smarty",tpl {path}                                            
     313 text files.
     312 unique files.                                          
       4 files ignored.

github.com/AlDanial/cloc v 1.83  T=0.46 s (671.2 files/s, 94684.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Smarty                         311           4651            910          38423
HTML                             1              2              0             28
-------------------------------------------------------------------------------
SUM:                           312           4653            910          38451
-------------------------------------------------------------------------------
```

This is much more accurate, thank you. (Those additional 100-odd files not detected are true HTML files with a `.tpl` extension; given my framework's workflow all output is processed by Smarty regardless.)

**Comment by AlDanial** [comment]
cool
