### ISSUE TITLE
Using the parameter --git --diff at the same time expects to display only the modified file

### ISSUE THREAD

**Issue by mms0536** [AlDanial/cloc#435]
Command example:cloc  --git --diff e6add3c3e2dd8ff32d62f953821213042f580e92~1 e6add3c3e2dd8ff32d62f953821213042f580e92
current: Calculate all files, unmodified files will also be counted
Expectation: I hope that I can control only the modified files through parameter control.

**Comment by AlDanial** [comment]
To spell this out, what you're asking for is rather than get two sets of files from
<pre>
git ls-tree --name-only -r HASH_L
git ls-tree --name-only -r HASH_R
</pre>
and diff'ing those, you'd rather see results just for files that come from
<pre>
git diff --name-only HASH_L HASH_R
</pre>
?  It makes sense (and will run more quickly).  I'm wondering what the new switch that triggers this should be called; would ``--git-diff`` be confusing?

**Comment by mms0536** [comment]
> To spell this out, what you're asking for is rather than get two sets of files from
> 
> git ls-tree --name-only -r HASH_L
> git ls-tree --name-only -r HASH_R
> and diff'ing those, you'd rather see results just for files that come from
> 
> git diff --name-only HASH_L HASH_R
> ? It makes sense (and will run more quickly). I'm wondering what the new switch that triggers this should be called; would `--git-diff` be confusing?

--git-diff will be well understood, after using this parameter, --git and --diff are no longer needed,Can I understand this?

**Comment by AlDanial** [comment]
Let me know if ``--git --diff`` in 1.86 work the way you expect.
