### ISSUE TITLE
Use of uninitialized value error

### ISSUE THREAD

**Issue by LakeRainSound** [AlDanial/cloc#453]
Thank you for the great  tool.
I use cloc v1.84.
When I use cloc for "springfox/springfox", it gave a error message.
```
Use of uninitialized value $2 in concatenation (.) or string at (eval 59) line 1.
Use of uninitialized value $3 in concatenation (.) or string at (eval 59) line 1.
Use of uninitialized value $4 in concatenation (.) or string at (eval 59) line 1.
```

What problems occur?

**Comment by AlDanial** [comment]
Can you post the file 'springfox' ?  I won't be able to figure out the problem unless I have input that can trigger it.

**Comment by LakeRainSound** [comment]
Sorry, “springfox/springfox” is a repository on GitHub. 
https://github.com/springfox/springfox

**Comment by AlDanial** [comment]
That problem has been fixed in the development version:
<pre>
/tmp> git clone https://github.com/springfox/springfox.git

/tmp> cloc springfox/
    1127 text files.
    1117 unique files.                                          
      64 files ignored.

github.com/AlDanial/cloc v 1.85  T=1.11 s (978.1 files/s, 111314.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JSON                            36             73              0          32200
Java                           651           7053          14276          31812
Groovy                         333           3790           4888          22871
AsciiDoc                         9            533             14           1894
Markdown                        15            281              0           1466
Gradle                          29            195             71           1302
JavaScript                       4             36             57            256
XML                              5             39             64            141
Bourne Shell                     1             21             22            129
YAML                             2              7              3            102
HTML                             1             14              1             60
DOS Batch                        1             23              2             59
CSS                              1              6              7             56
-------------------------------------------------------------------------------
SUM:                          1088          12071          19405          92348
-------------------------------------------------------------------------------
</pre>

Can you try cloc from its git master branch?

**Comment by LakeRainSound** [comment]
OK, I'll try it.
