### ISSUE TITLE
Language R ignored

### ISSUE THREAD

**Issue by Chr96er** [AlDanial/cloc#46]
According to http://sourceforge.net/p/cloc/feature-requests/69/ the language R should be analyzed since 1.62. When applying cloc 1.64 (or 1.62) on https://github.com/Dennis1989/MOCK I it only finds C++, XML, and Headers.

**Comment by AlDanial** [comment]
Strange, works for me:

<pre>
> cloc ~/Downloads/MOCK-master.zip 
     180 text files.
     173 unique files.                                          
     127 files ignored.

https://github.com/AlDanial/cloc v 1.65  T=0.39 s (141.3 files/s, 9571.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               27            357            700           1391
C++                             20             81            306            745
XML                              1              0              3             87
C/C++ Header                     7             14             14             28
-------------------------------------------------------------------------------
SUM:                            55            452           1023           2251
-------------------------------------------------------------------------------
</pre>

What do you get for

<pre>
cloc --version
</pre>

?  I'm using the current git master version, https://github.com/AlDanial/cloc/blob/master/cloc

**Comment by AlDanial** [comment]
Ooops, nevermind, I saw you're using 1.62 and 1.64.  Can you give it a try with the git master?

I plan to release the next version, 1.66, by the end of this month.

**Comment by Chr96er** [comment]
Same result here, no R files recognized. Besides that, the output is the same as yours. Except for the header:
     290 text files.
     220 unique files.                                          
     308 files ignored.
The only difference I can see, is that I call cloc like this:
    perl cloc MOCK-PESA-II
Where MOCK-PESA-II is the path to the repository's folder. I didn't want to install winzip, but I guess that can't be the reason.

For the moment I'd be grateful if you could provide the statistics for the subdirectories MOCK and PESAII.

If there's anything I can do to help debug this, let me know, although that will have to wait a couple of days.

**Comment by AlDanial** [comment]
Your mention of winzip indicates you're running on a Windows machine so the problem most likely has to do with that somehow.

Here are the stats for your two subdirectories:

<pre>
/tmp/MOCK-master> ls
additions/  Documentation/  MOCK/  PESAII/  README.md

/tmp/MOCK-master> cloc MOCK
     115 text files.
     115 unique files.                                          
      83 files ignored.

https://github.com/AlDanial/cloc v 1.65  T=0.15 s (218.4 files/s, 16227.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               11            171            458            850
C++                             14             60            259            524
C/C++ Header                     7             14             14             28
-------------------------------------------------------------------------------
SUM:                            32            245            731           1402
-------------------------------------------------------------------------------

/tmp/MOCK-master> cloc PESAII/
      34 text files.
      34 unique files.                              
      18 files ignored.

https://github.com/AlDanial/cloc v 1.65  T=0.05 s (314.9 files/s, 14857.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               10             69            144            253
C++                              6             21             47            221
-------------------------------------------------------------------------------
SUM:                            16             90            191            474
-------------------------------------------------------------------------------
</pre>

Since our counts for # text and # ignored files differ it suggests cloc on Windows is ignoring R files for some reason.  We can use the <code>--ignored</code> option to figure out why:

<pre>
cloc --ignored ign.txt MOCK-master/
</pre>

This will create a file, <code>ign.txt</code>, which tells which files it ignored and why.  Let me know what it says for R files.

**Comment by Chr96er** [comment]
Thanks a lot for the stats!

That's right, I'm running cloc on windows. I attached the output using the `--ignored` option.
[ign.txt](https://github.com/AlDanial/cloc/files/82859/ign.txt)

**Comment by AlDanial** [comment]
With entries like
<pre>
MOCK-PESA-II/MOCK/R/MOCK-package.R: language unknown (#3)
</pre>
it sure looks like the Windows exe doesn't recognize R.  

If you have the opportunity to install a Perl interpreter on your Windows box (eg Strawberry Perl or ActiveState Perl) you'll have the benefit of running with the latest source.  Otherwise you'll need to wait until the next release (end January).

**Comment by AlDanial** [comment]
Took a while to get access to a Windows machine to see what exactly was going on.  Found the problem, was related to the code, on Windows, forcing file extensions to match the known extensions in lower case and R only had .R defined.  Works now with git commit 7e3995d.
