### ISSUE TITLE
Diff file in Folder

### ISSUE THREAD

**Issue by Sori31** [AlDanial/cloc#498]
I cannot compare file in the directory
The 2 directory structures to compare are as follows
![image](https://user-images.githubusercontent.com/62527864/86534947-fb986900-bf06-11ea-80ce-7a571dfb769c.png)

I just want to compare the file in the directory : C:\SourceNew\P_EDI_BookF8.sql
C:\cloc.exe --match-f="^P_EDI_BookF8.sql" --Diff "C:\SourceOld" "C:\SourceNew" --unicode --skip-win-hidden --skip-uniqueness --by-file 

Result :  three file 
![image](https://user-images.githubusercontent.com/62527864/86535105-0273ab80-bf08-11ea-845c-cdb15cb1b116.png)

Can you assist me

I want result : 
![image](https://user-images.githubusercontent.com/62527864/86535474-cc83f680-bf0a-11ea-9aa6-755f77352e71.png)

If select two file, result 
![image](https://user-images.githubusercontent.com/62527864/86535518-1bca2700-bf0b-11ea-9878-d9e17e905b51.png)

**Comment by AlDanial** [comment]
Post a zip file with the two folders.  The images above don't offer much.

**Comment by Sori31** [comment]
I have tow folders
   1/  C:\SourceOld\P_EDI_BookF8.sql
   2/ C:\SourceNew\P_EDI_BookF8.sql
       C:\SourceNew\file_new\P_EDI_BookF8.sql 




When difference on folders, I want diff file tại  C:\SourceNew\file_new\P_EDI_BookF8.sql 
     C:\cloc.exe --match-f="^P_EDI_BookF8.sql" --Diff "C:\SourceOld" "C:\SourceNew" --unicode --skip-win-hidden --skip-uniqueness --by-file
 But the results are not expected
   
![image](https://user-images.githubusercontent.com/62527864/86909578-7bf6de00-c142-11ea-84e8-8701ff468653.png)

But I want result : 
![image](https://user-images.githubusercontent.com/62527864/86910078-4ef6fb00-c143-11ea-87f3-001a3d6697af.png)

File Source : 
[Download.zip](https://github.com/AlDanial/cloc/files/4890172/Download.zip)

**Comment by AlDanial** [comment]
The diff logic has changed slightly between 1.84 and the current development version.  I get this result:
<pre>
> cloc --diff SourceOld SourceNew --unicode --skip-win-hidden --skip-uniqueness --by-file

github.com/AlDanial/cloc v 1.87  T=0.01 s (291.5 files/s, 12098.3 lines/s)
--------------------------------------------------------------------------------------
File                                             blank        comment           code
--------------------------------------------------------------------------------------
SourceNew/file new/P_EDI_BookF8.sql
 same                                                0              0              0
 modified                                            0              0              0
 added                                              24             36             23
 removed                                             0              0              0
SourceOld/P_EDI_BookF8.sql
 same                                               24             36             23
 modified                                            0              0              0
 added                                               0              0              0
 removed                                             0              0              0
--------------------------------------------------------------------------------------
SUM:
 same                                               24             36             23
 modified                                            0              0              0
 added                                              24             36             23
 removed                                             0              0              0
--------------------------------------------------------------------------------------
</pre>
Is that what you expect?

**Comment by Sori31** [comment]
Case:  In two directories only counter file select
EX :  Counter file SourceNew/P_EDI_BookF8.sql 
 C:\cloc.exe --match-f="^P_EDI_BookF8.sql" --Diff "C:\SourceOld" "C:\SourceNew" --unicode --skip-win-hidden --skip-uniqueness --by-file
But the results are not expected

**Comment by AlDanial** [comment]
With the changes made for #521 I now get this result which looks correct to me.  Once again the issue is whether or not duplicate files in the same collection (ie ``SourceOld`` or ``SourceNew``) are kept or counted.
<pre> 
> md5sum ./SourceOld/P_EDI_BookF8.sql "./SourceNew/file new/P_EDI_BookF8.sql" ./SourceNew/P_EDI_BookF8.sql
d3be55a57fc69dd6d1b24e3cbdf16d32  ./SourceOld/P_EDI_BookF8.sql
d3be55a57fc69dd6d1b24e3cbdf16d32  ./SourceNew/file new/P_EDI_BookF8.sql
d3be55a57fc69dd6d1b24e3cbdf16d32  ./SourceNew/P_EDI_BookF8.sql


> cloc --unicode --skip-win-hidden --diff SourceOld/ SourceNew

github.com/AlDanial/cloc v 1.89  T=0.01 s (79.0 files/s, 6558.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SQL
 same                            1             24             36             23
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         0              0              0              0
-------------------------------------------------------------------------------
SUM:
 same                            1             24             36             23
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         0              0              0              0
-------------------------------------------------------------------------------



> cloc --unicode --skip-win-hidden --skip-uniqueness --by-file --diff SourceOld/ SourceNew

github.com/AlDanial/cloc v 1.89  T=0.01 s (304.3 files/s, 12629.3 lines/s)
--------------------------------------------------------------------------------------
File                                             blank        comment           code
--------------------------------------------------------------------------------------
SourceNew/file new/P_EDI_BookF8.sql
 same                                                0              0              0
 modified                                            0              0              0
 added                                              24             36             23
 removed                                             0              0              0
SourceOld/P_EDI_BookF8.sql
 same                                               24             36             23
 modified                                            0              0              0
 added                                               0              0              0
 removed                                             0              0              0
--------------------------------------------------------------------------------------
SUM:
 same                                               24             36             23
 modified                                            0              0              0
 added                                              24             36             23
 removed                                             0              0              0
--------------------------------------------------------------------------------------
</pre>
