### ISSUE TITLE
Diff two folder, folder name the same 

### ISSUE THREAD

**Issue by Sori31** [AlDanial/cloc#521]
I have structure : (attch) .
[Baseloc.zip](https://github.com/AlDanial/cloc/files/5267010/Baseloc.zip)

Source old : Baseloc\Test 188
Source new : Baseloc\Test188New\Test 188

C:\cloc.exe --Diff "C:\Baseloc\Test 188" "C:\Baseloc\Test188New\Test 188" --unicode --ignore-case-ext --skip-win-hidden --skip-uniqueness --by-file

![the same folder](https://user-images.githubusercontent.com/62527864/93993419-ebcb4b00-fdb8-11ea-823d-67f8156f1cd4.png)
 Help me

**Comment by AlDanial** [comment]
The problem is caused by the file pairing logic failing but it looks like it is related to Windows somehow.  On Linux I get
<pre>
> cloc  --unicode --skip-win-hidden --skip-uniqueness --by-file --diff "/tmp/issue521/Test 188" "/tmp/issue521/Test188New/Test 188"

github.com/AlDanial/cloc v 1.88  T=0.01 s (330.1 files/s, 1650.7 lines/s)
-----------------------------------------------------------------------------------
File                                          blank        comment           code
-----------------------------------------------------------------------------------
/tmp/issue521/Test 188/Test1.sql
 same                                             0              0              6
 modified                                         0              0              0
 added                                            0              0              0
 removed                                          0              0              4
/tmp/issue521/Test 188/UP0PB.sql
 same                                             0              0             10
 modified                                         0              0              0
 added                                            0              0              0
 removed                                          0              0              0
-----------------------------------------------------------------------------------
SUM:
 same                                             0              0             16
 modified                                         0              0              0
 added                                            0              0              0
 removed                                          0              0              4
-----------------------------------------
</pre>

Try this
<pre>
cd Baseloc
C:\cloc.exe --diff ".\Test 188" ".\Test188New\Test 188" --unicode --ignore-case-ext --skip-win-hidden --skip-uniqueness --by-file
</pre>

**Comment by Sori31** [comment]
I using 
cd Baseloc
C:\cloc.exe --diff ".\Test 188" ".\Test188New\Test 188" --unicode --ignore-case-ext --skip-win-hidden --skip-uniqueness --by-file


![2020-09-24_115937](https://user-images.githubusercontent.com/62527864/94102947-7f565780-fe5d-11ea-8b7c-635d858e9a2f.png)

**Comment by AlDanial** [comment]
I made several Windows-specific fixes for ``--diff``; please try the latest code in https://github.com/AlDanial/cloc/commit/dc1551456c7c5dce1be5f3d72ff2e28ba0db7790.  These fixes will likely resolve #498 and perhaps also #501.

**Comment by Sori31** [comment]
I pull version new on Git -> Build Version cloc189
 Result : file test1.sql non - diff
![2020-09-28_134321](https://user-images.githubusercontent.com/62527864/94399095-f870ea00-0190-11eb-9f29-c044487795b6.png)

**Comment by AlDanial** [comment]
This is good news, the result is correct--or it would be correct if you run with ``--skip-uniqueness``.  The problem you're seeing now is because the files ``Test 188/Test1.sql`` and ``Test 188/UP0PB.sql`` are identical:
<pre>
md5sum "Test 188/Test1.sql" "Test 188/UP0PB.sql" 
175ac6484c30de4541578e8655c21d8b  Test 188/Test1.sql
175ac6484c30de4541578e8655c21d8b  Test 188/UP0PB.sql
</pre>
Before cloc counts files, it first makes a list of unique files so that it does not count the same content twice.  The duplicate files are ignored.  Here that means ``Test 188/Test1.sql`` is ignored.  Therefore there is no counterpart to ``Test188New/Test 188/Test1.sql`` and it looks like this file was added.
