### ISSUE TITLE
cloc-1.88.exe classifies a file named ICONFIG.H as a text file rather than a C/C++ Header file

### ISSUE THREAD

**Issue by savignac** [AlDanial/cloc#544]
I found that cloc-1.88.exe classifies a file named ICONFIG.H as a text file rather than a C/C++ Header file.  If I change the name of the file for .H++ or .HPP, everything is fine and it is classified as a C/C++ Header file. If I change the name of the file to ABC.H , everything is fine again and it classified as a C/C++ Header file. But a file named ICONFIG.H is rather always classified as a text file. 

It used to work until cloc-1.86.exe. Behavior has changed in cloc-1.88.exe.

Anything I can do to do fix this using the filter switches?

**Comment by AlDanial** [comment]
``iconfig.h`` is a file explicitly ignored by cloc since this is part of an Imake build.  The relevant line in the source code (of the current git HEAD) is 9753 which is in a batch of files which are excluded:
<pre>
 9751    'Entries'     => 1,
 9752    'FAQ'         => 1,
 9753    'iconfig.h'   => 1, # Skip "iconfig.h" files; they're used in Imakefiles.
 9754    'INSTALL'     => 1,
</pre>

Now that I think about it, I can't come up with a good reason ``iconfig.h`` should be skipped--who cares if it is part of Imake or not?  I'll remove this line so the next release of cloc will count these.
