### ISSUE TITLE
File Paths on windows in the ignored file are partially lower case

### ISSUE THREAD

**Issue by Roemer** [AlDanial/cloc#554]
In the current nightly, some file paths in the ignored file that is generated are lowercase.
The cases I found where they are lowercase are:
- listed in $Not_Code_Extension
- language unknown
- duplicate of ... here both the filename and the text in the duplicate of... is lowercase)

**Comment by AlDanial** [comment]
Thanks for reporting this.  Uppercase/lowercase in Windows is an endless source of headache.

**Comment by AlDanial** [comment]
Give the latest a shot, let me know if it looks right.

**Comment by mitchblank** [comment]
Somewhat related:
```
$ git clone https://github.com/AlDanial/cloc.git
Cloning into 'cloc'...
[...]
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'tests/inputs/issues/540/Hello.f'
  'tests/inputs/issues/540/hello.f'
```
(this is on OS/X, but the same case-insensitivity issue would exist on Windows)

**Comment by AlDanial** [comment]
@mitchblank : the duplication is exactly the point for this particular unit test.  I'm not aware of a way to have git suppress the warning.

**Comment by mitchblank** [comment]
Perhaps create the files when the test runs (and ideally skip the test if the filesystem is likely to be case-insensitive) rather than checking the files into git directly?

The warning is completely legit -- on a case-insensitive filesystem you can't have two separate files named `Hello.f` and `hello.f` so there isn't really any correct way to make git check both files out at once

**Comment by AlDanial** [comment]
"Perhaps create the files when the test runs":  good idea, I'll remove the link from git and create it at runtime
