### ISSUE TITLE
Terminates file directory at a space (on windows)

### ISSUE THREAD

**Issue by adeshere** [AlDanial/cloc#561]
If you specify a folder that has a space in it, 

cloc-18.8 C:\maindir\sub dir\*.C  or  cloc-18.8 "C:\maindir\sub dir\*.C"

you get

0 text files.
       0 unique files.
       0 files ignored.

1 error:
Unable to read: C:\maindir\sub

**Comment by AlDanial** [comment]
Use single quotes instead of double: 
<pre>
C:\> dir "tmp\a b"  
 Directory of C:\tmp\a b

02/09/2021  08:18 PM    <DIR>          .
02/09/2021  08:18 PM    <DIR>          ..
09/11/2020  09:50 AM               196 C-Ansi.c
09/11/2020  09:50 AM               199 hello.C
09/11/2020  09:50 AM                21 temp.c
               3 File(s)            416 bytes
               2 Dir(s)  406,540,234,752 bytes free

C:\> cloc-1.88.exe 'tmp\a*'
       3 text files.
       3 unique files.
       1 file ignored.

github.com/AlDanial/cloc v 1.88  T=0.09 s (32.6 files/s, 260.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C                                3              4              4             16
-------------------------------------------------------------------------------
SUM:                             3              4              4             16
-------------------------------------------------------------------------------
</pre>

**Comment by AlDanial** [comment]
Also you need an extra path separator before the ``*.C`` : ``cloc-1.8.8.exe 'C:\maindir\sub dir\*.C'``
