### ISSUE TITLE
Rust multi-line string containing empty line causes cloc to produce incorrect code count

### ISSUE THREAD

**Issue by saifali-ch** [AlDanial/cloc#562]
**Problem**
I ran **scc** and **cloc** against a repo and the num of **Rust** code lines returned by both tools differed significantly. 

**What i tried then**
So, I tried to run both tools against a single file. Again results differed significantly. 
Then, I tried to reduce the amount of code so I can see where the issue is.
And eventually, I came to know that the problem is with multi-line strings. 
**I am not a Rust deveoper but to me the problem seems to be in multi-line strings.**

Below is the code snippet, you can see this in pictures as well.

```
const TEMPLATE: &str = "\
{bin} {version}
{author}
{about}

USAGE:{usage}

ARGS:
{positionals}

OPTIONS:
{unified}";
```
_BTW, I was using both tools for this repo_ ---> **https://github.com/BurntSushi/ripgrep**

**To Reproduce**
you can run both scc and cloc against it.

### cloc
![image](https://user-images.githubusercontent.com/54573967/107126113-d40be380-68cf-11eb-9c55-a47993db6e07.png)

## scc
![image](https://user-images.githubusercontent.com/54573967/107126136-edad2b00-68cf-11eb-8b26-c59e4ff92151.png)

**Comment by AlDanial** [comment]
scc gives more correct results because it does an actual lexical parse of the code while cloc merely applies regex rules without knowledge of things like multiline strings.  Internally, cloc first skips over blank lines in a source file, in this case the blanks within the multiline string.  This is a design limitation of cloc (ref https://github.com/AlDanial/cloc#limitations-) rather than a bug.
