### ISSUE TITLE
what is the language named diff? 

### ISSUE THREAD

**Issue by caork** [AlDanial/cloc#583]
<img width="916" alt="Screen Shot 2021-03-29 at 11 36 17 AM" src="https://user-images.githubusercontent.com/34786132/112783923-fd045580-9082-11eb-91e0-21d1484dcfa4.png">

there are over 100000 code lines about language diff. I can't find any file named *.diff in the whole project, is that the historical code about every git commits?

**Comment by caork** [comment]
I found that if I create a new project pulled by GitHub, the diff lines will disappear.

**Comment by AlDanial** [comment]
A diff file contains the output of the ``diff`` command (on Unix like OS) usually saved so that the diff can be used to update the old file(s) to the new version(s).  These are also called patch files.  If you run cloc with ``--by-file --csv`` you'll be able to tell which files cloc identified as diff.
Here's an example https://patch-diff.githubusercontent.com/raw/AlDanial/cloc/pull/584.diff

**Comment by caork** [comment]
thanks! I got it.
