### ISSUE TITLE
Please add code complexity metrics

### ISSUE THREAD

**Issue by llothar** [AlDanial/cloc#593]
Adam Thornhill who wrote the books "Your Code As a Crime Scene: Use Forensic Techniques to Arrest Defects, Bottlenecks, and Bad Design in Your Programs"  and "Software Design X-Rays: Fix Technical Debt with Behavioral Code Analysis"  describes and uses a nice language agnostic complexity measurement that works very well with all kinds of source code. Almost as well as the traditional complex metrics like McCabe's cyclomatic complexity which requires exact language parsing 

Its the number of indentation characters (spaces and/or tabs) in front of code lines.
 
It's a five minute task to implement but finding the code lines in all the real languages is the real work and that work is already done by cloc. It also nicely fits into the idea of cloc and maybe we can add -4 option (similar to -3) to add this metric.

I'm not a perl programmer and definitely never want become one so unfortunately i can't provide a patch.

**Comment by AlDanial** [comment]
My recommendation is to use a counter such as [scc](https://github.com/boyter/scc/) which does complexity analysis rigorously.

Thornhill's idea is cute but meaningless for real-world code that spans multiple lines (bear in mind cloc counts physical, not logical code lines).  Consider this simple header file from the Python language, https://github.com/python/cpython/blob/main/Parser/string_parser.h.  Complexity is 0 but Thornhill's method scores it 8 since lines 40 and 41 are indented by 32 spaces if you treat 4 spaces as one indent level.  Then, on the flip side for complex code Thornhill's method gives a substantial undercount (https://github.com/python/cpython/blob/main/Objects/call.c is an example).

I'm going to pass on this one.
