### ISSUE TITLE
Memory issues when parsing JSON content

### ISSUE THREAD

**Issue by oli99sc** [AlDanial/cloc#599]
**Describe the bug**
I am running cloc version 1.90 on mac on a git repository which happens to have a big json file inside. 
The json file consists of a single line without a line break at the end. 
The files size is 30 MB

Command I run is: 

cloc OneObject_1.json --vcs=git --json --quiet --max-file-size=10

This process uses > 3,5 GB of memory for the analysis
a) Why does cloc process the files with max-file-size=10?
b) why is it consuming so much memory. 

**cloc; OS; OS version**
 - cloc version: 1.90
 - If running the cloc source, Perl version: This is perl 5, version 18, subversion 4 (v5.18.4)
 - OS (eg Linux, Windows, macOS, etc): MacOS
 - OS version: 10.15.7

**To Reproduce**
Steps one can follow reproduce the behavior you're seeing.
Unfortunately I can not share the file directly. 
The format of that file is a bit weird.
It is a json, consisting of an array of strings. 
Each string however represents a quoted json object by itself: 
["{\"attribute1\": 1, \"attribute2\": \"j\", \"attribute3\": 0.0, .... \"attribute48\": \"j\"}\n", <many of these> ]

**Expected result**
A concise description of what you expected to happen.

File is ignored when bigger then max-file-size.
And even if not bigger, does not consume so much memory. 

**Additional context**
Consumed memory seems to be ~1GB per 10 MB of text in the file

**Comment by AlDanial** [comment]
a)  See the last two lines of the documentation for ``--max-file-size`` :
<pre>
  --max-file-size=<MB>      Skip files larger than <MB> megabytes when               
                        traversing directories.  By default, <MB>=100.   
                        cloc's memory requirement is roughly twenty times
                        larger than the largest file so running with    
                        files larger than 100 MB on a computer with less 
                        than 2 GB of memory will cause problems.          
                        Note:  this check does not apply to files    
                        explicitly passed as command line arguments.     
</pre>
The reasoning is if you tell cloc "count this file", it will ignore all filter rules and count it.  Filters only apply when cloc has to hunt for files on its own.

b) I don't have the exact explanation for the memory explosion but the root cause is that your JSON file has 30 MB in one line.  I used this small program
<pre>
#!/usr/bin/env perl
# ./big_json 1000000 > j.json # 30 MB
my $n = shift @ARGV;
my $json = "[\"{";
foreach (1..$n) {
    $json .= sprintf "\"attribute_%08d\" : %d, ", $_, $_;
    $json .= "\n" unless $_ % 100; # entries per line
}
$json =~ s/,\s*$//;
print $json, "}\"]\n";
</pre>
to create arbitrarily-sized JSON files that match your description (``jsonlint`` says they are illegal, but that's not relevant here).  If you comment out the line that ends with "entries per line" so that the output has just one line, cloc will use about 2.8 GB of memory for a 30 MB JSON file.  If you leave the line active so that the 30 MB file is split into 10,000 lines, cloc runs so quickly I can't measure memory use--but I imagine it is small.

**Comment by oli99sc** [comment]
The memory issue also occures when using . In the root dir of the repository. -v4 shows that the file is being processed.

**Comment by oli99sc** [comment]
Ah, and I see now that the backslash quoting of the “ characters within each of the string entries in the array got lost when pasting into the github issue. 
Anyway I am not saying cloc should support the crazy file format. File size checking however would be great.

**Comment by AlDanial** [comment]
File size checking works for me:
<pre>
> cd /tmp

/tmp> mkdir 599

/tmp> ~/big_json 1000000 > 599/j.json

/tmp> ls -l 599/j.json
-rw-rw-r-- 1 al al 30898900 Jul  9 07:28 599/j.json

/tmp> cloc --max-file-size 10 --ignored ig.txt 599
       0 text files.
       0 unique files.                              
Wrote ig.txt
       1 file ignored.

/tmp> cat ig.txt 
599/j.json:  file size of 29.4674873352051 MB exceeds max file size of 10 MB

# now repeat with .
/tmp> cd 599

/tmp/599> cloc --max-file-size 10 --ignored ig.txt .
       0 text files.
       0 unique files.                              
Wrote ig.txt
       1 file ignored.

/tmp/599> cat ig.txt 
./j.json:  file size of 29.4674873352051 MB exceeds max file size of 10 MB
</pre>
What happens when you repeat these commands?

**Comment by oli99sc** [comment]
When I run: 
`cloc . --vcs=git   --max-file-size 1  --ignored ig.txt`
dit does not ignore the file (and it takes quite long),

however when I run 
`cloc .   --max-file-size 1  --ignored ig.txt`

it does ignore the file (and is super quick)

**Comment by AlDanial** [comment]
Definitely a bug, thanks for clarifying. Should work now.

**Comment by oli99sc** [comment]
Thx for fixing, this is very much appreciated!
