### ISSUE TITLE
Including multiple languages ignores all files

### ISSUE THREAD

**Issue by crystalfp** [AlDanial/cloc#603]
**Describe the bug**
Including multiple languages ignores all files.

**cloc; OS; OS version**
 - cloc version: 1.90
 - If running the cloc source, Perl version:
 - OS (eg Linux, Windows, macOS, etc): Windows
 - OS version:  Windows 10 64bits

**To Reproduce**
Steps one can follow reproduce the behavior you're seeing.
Including a single language or not using the `--include-lang` option works. For example:
```
$ cloc client server common --include-lang=TypeScript --fullpath
--not-match-d=node_modules --timeout=0
     301 text files.
     274 unique files.
     234 files ignored.

github.com/AlDanial/cloc v 1.90  T=4.62 s (15.8 files/s, 2836.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
TypeScript                      73           2324           1582           9193
-------------------------------------------------------------------------------
SUM:                            73           2324           1582           9193
-------------------------------------------------------------------------------
```
It works on the same directories' html files if I use `--include-lang=HTML`
But if I ask for both languages using `--include-lang=HTML,TypeScript` I have:
```
     301 text files.
     274 unique files.
     307 files ignored.
```
and no count.
Identical behavior if I use `--include-ext=ts,html`

**Expected result**
Receive back a table with two lines, one for the HTML files counts, one for Typescript.

**Additional context**
I use cloc installed with npm, but I think the problem is better put here.
Initially I opened the issue here: https://github.com/kentcdodds/cloc/issues/21#issue-961604781

**Comment by AlDanial** [comment]
I'm unable to duplicate this problem on either Windows or Linux.  Using the ``common`` directory in the attached zip file I get
<pre>
cloc common --include-lang=TypeScript,HTML --fullpath --not-match-d=node_modules --timeout=0
       5 text files.
       5 unique files.                              
       0 files ignored.

github.com/AlDanial/cloc v 1.91  T=0.01 s (462.6 files/s, 47553.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
TypeScript                       4             53             39            416
HTML                             1              0              0              6
-------------------------------------------------------------------------------
SUM:                             5             53             39            422
-------------------------------------------------------------------------------
</pre>
What happens when you try to count this particular directory?
[issue_603.zip](https://github.com/AlDanial/cloc/files/6946950/issue_603.zip)

**Comment by crystalfp** [comment]
It works for your dir and for my previous dirs if I install `cloc` inside the project and call it with `npx cloc`. It fails for your directory and mine if I install it globally.

**Comment by AlDanial** [comment]
That's a situation I've never heard of before.  Rather than using the Node version, can you grab the official Windows exe from https://github.com/AlDanial/cloc/releases/download/v1.90/cloc-1.90.exe, put that somewhere on your path, then try again?

**Comment by crystalfp** [comment]
The exe works without problems for your and mine examples.
