### ISSUE TITLE
can not recognize CMakeLists.txt

### ISSUE THREAD

**Issue by luhuachuixue** [AlDanial/cloc#611]
**Describe the bug**
can not recognize CMakeLists.txt.

**cloc; OS; OS version**
 - cloc version: 1.90
 - If running the cloc source, Perl version:
 - OS (eg Linux, Windows, macOS, etc): Windows
 - OS version: Windows 10 21H2

**To Reproduce**
run cloc in any project, which has a CMakeLists.txt.

**Expected result**
show CMake type.

**Additional context**
according to test, since cloc 1.88, there has been this case, while 1.86 could recognize CMakeLists.txt.
one possible reason may be recognize CMakeLists.txt as common text file

**Comment by AlDanial** [comment]
Thanks for reporting this issue.  The root cause is an uppercase/lowercase issue with "CMakeList.txt" -- cloc recognizes the mixed case filename but on Windows the directory scanner sees it as "cmakelist.txt" and so it is ignored.
I will be tied up for the next 2-3 weeks so it will be a bit before I'm able to fix the code.

**Comment by RabbitSeries** [comment]
@AlDanial This works for cloc . without filter options, but fails for --include-ext=CMakeLists.txt for me.
