### ISSUE TITLE
--count-and-diff --out=xxxx     exception

### ISSUE THREAD

**Issue by wengjianchuan** [AlDanial/cloc#675]
cmd :cloc --count-and-diff --out=analysis E:\MyCodeWork\PythonWorkspace\FastCFS_bak E:\MyCodeWork\PythonWorkspace\FastCFS
exception：Unable to write to analysis.E:_MyCodeWork_PythonWorkspace_FastCFS_bak.E:_MyCodeWork_PythonWorkspace_FastCF

![1661411940588](https://user-images.githubusercontent.com/25163838/186600644-f87b5644-aa01-4144-9278-32fd430a0634.png)
S

**Comment by AlDanial** [comment]
The problem comes from the leading ``E:`` in front of the two directories (the last two command line arguments).  cloc tries to create a windows file name based on ``file_name`` plus the embedded ``E:`` and that isn't allowed.  Until I fix this, run without the letter drive:
<pre>
cloc.exe --count-and-diff --out=file_name \MyCodeWork\PythonWorkspace\FastCFS_bak \MyCodeWork\PythonWorkspace\FastCFS
</pre>

**Comment by AlDanial** [comment]
Fixed in https://github.com/AlDanial/cloc/commit/0995e8ce3abf0a690e46da4a0ad880ed376dc57a .
