### ISSUE TITLE
Bug on --strip-str-comments

### ISSUE THREAD

**Issue by Christina96** [AlDanial/cloc#719]
When a  file has a string with // inside (eg. HTTP://, file:// etch.) then the clock removes it because it thinks that is a comment (in languages that // is a comment). 
For example, I ran it on [jdk]( https://github.com/openjdk/jdk) and on file "TestFinalizerStatisticsEvent.java" (and other files also) if you run it, you will see the bug.

 - cloc version: 1.96
 - OS: Linux and macOS
 - OS version:

**To Reproduce**
Run: ```cloc ./jdk --skip-uniqueness --processes=8 --strip-comments=BAK --original-dir```

On .BAK files you will see the problem if they have a string with // on it.

**Before removing comments**
```
switch (overridingClass.getName()) {
    case TEST_CLASS_NAME: {
        Asserts.assertTrue(event.getString("codeSource").startsWith("file://"));
        foundTestClassName = true;
        break;
    }
    case TEST_CLASS_UNLOAD_NAME: {
        foundTestClassUnloadName = true;
        break;
    }
}
```

**After removing comments**
```
switch (overridingClass.getName()) {
    case TEST_CLASS_NAME: {
        Asserts.assertTrue(event.getString("codeSource").startsWith("file:
        foundTestClassName = true;
        break;
    }
    case TEST_CLASS_UNLOAD_NAME: {
        foundTestClassUnloadName = true;
        break;
    }
}
```

**Languages that I have notices this problem**
Java, C, C++,  C#

**Comment by AlDanial** [comment]
Unfortunately there's no straightforward way (at least I can't think of one) to solve this with a regex-based tool such as cloc.  Only a true language parser can make sense of what's in a string.  cloc's method is approximate rather than perfect.

Having said that, I can think of a work-around although it is painful and unlikely to be worth the trouble.  You could try to find files with such problematic strings using something like
<pre>
find ./jdk -type f -name "*.java" -o -name "*.cpp" | xargs grep -l -P '"(http|https|file)://"' 
</pre>
then use perl to modify the string by removing the inner  ``/``, ie,
<pre>
perl -pi -e 's{"(http|https|file)://"}{"$1: /"}g'   list_of_files_matched_by_grep
</pre>
then run ``cloc --strip-comments=BAK`` on this set and finally restore the missing ``/`` in this set:
<pre>
perl -pi -e 's{"(http|https|file): /"}{"$1://"}g'   list_of_files_matched_by_grep
</pre>

As I said though, that's pretty extreme.  One would have to be quite desperate to bother with all that.
