### ISSUE TITLE
cloc counts "#if 0" lines as code

### ISSUE THREAD

**Issue by fefe17** [AlDanial/cloc#767]
When running cloc against some code of mine, I noted that it does not appear to have any support for the C preprocessor.

It's a well known idiom in C to comment out large chunks of code by adding an "#if 0" at the start and an "#endif" at the end. cloc counts all that lines as code.

I would also like to give cloc regex for detecting unit tests.
In my code, for example, there is an #ifdef UNITTEST ... #endif in every file that unit tests. To run the tests, you do

  $ gcc -o t file.c -DUNITTEST && ./t

As with all good unit testing, I have mode lines of unit tests than I have lines of actual code.
I would like cloc to either count those as comments, or, preferably, add a new category besides comments and code.

**Comment by AlDanial** [comment]
It's an interesting idea but I don't see how I'd implement it in cloc. The behavior you're currently seeing is mentioned as item 6 of the [Limitations](https://github.com/AlDanial/cloc#limitations-) section of the docs.  cloc is regex-based and there's no regex I know of that can associate an `#ifdef` with its paired `#endif`.

If you can think of a way I'll consider it, otherwise will have to decline.
