### ISSUE TITLE
Add new lang (liquid)

### ISSUE THREAD

**Issue by reggi** [AlDanial/cloc#78]
File extension: 

```
.liquid
```

Comment syntax

```
{% comment %}
This won't show up when you do View Source in browser.
{% endcomment %}
```

I'd love to add this into my project pronto :smile:

Added the following to `my_definitions.txt`

```
liquid
    extension liquid
```

Then ran `cloc` and got an error.

```
$ cloc project/ --read-lang-def=my_definitions.txt
Can't use an undefined value as an ARRAY reference at /usr/local/bin/cloc line 6877.
```

**Comment by reggi** [comment]
Also because liquid contains `HTML` we'd want to include html comments as another comment syntax.

**Comment by AlDanial** [comment]
git commit dc743e9 adds support for liquid.  The business of writing this language's filter with --write-lang-def and reading it back with --read-lang-def will require further mods because this adds for the first time start and end comment markers with whitespace in them.  

Nonetheless I tested a trivial file with the new code and it seems to work.
