### ISSUE TITLE
Terraform support

### ISSUE THREAD

**Issue by syn-4ck** [AlDanial/cloc#791]
**If you want an unsupported language added, provide:**
 - language name: Terraform
 - file extension(s): .tf
 - method(s) of commenting text: # or // (one-line) and /* */ (block): https://developer.hashicorp.com/terraform/language/syntax/configuration#comments
 - location of sample code: https://github.com/futurice/terraform-examples/blob/master/generic/docker_compose_host/main.tf

**Comment by AlDanial** [comment]
Terraform's `.tf` file extension is also used by HCL, Hashicorp's Configuration Language (ref. https://developer.hashicorp.com/terraform/language/syntax/configuration).  cloc works with many languages that share extensions so that in itself isn't an issue.  The issue is that Terraform and HCL code looks indistinguishable; I don't see a way for cloc to look at a block of code from a `.tf` file and figure out whether it is Terraform or HCL.

Example HCL code can be seen here: https://www.nomadproject.io/docs/job-specification/index.html

Can you think of a way to identify one language over another?

**Comment by syn-4ck** [comment]
Sorry, I didn't see that HCL is supported. I think the actual implementation is the BEST one. Thanks.
