### ISSUE TITLE
When Japanese is specified in the report-file argument, the file name is not output correctly.

### ISSUE THREAD

**Issue by TomeSq** [AlDanial/cloc#801]
**Describe the bug**
There was no problem with 1.94, but when Japanese is specified for the report-file argument in later versions, the specified file name is not output.

**cloc; OS; OS version**
 - cloc version:1.98
 - If running the cloc source, Perl version: exe
 - OS (eg Linux, Windows, macOS, etc): Windows 11
 - OS version:23H2

**To Reproduce**
```bat
>cloc-1.98.exe --diff old.txt new.txt "--report-file=あ.txt" --windows --verbose
Using temp file list [C:\Users\foo~1\AppData\Local\Temp\V_7sPGkjUt]
       1 text file.
Using temp file list [C:\Users\foo~1\AppData\Local\Temp\yaJhiureAo]
       1 text file.
       0 files ignored.
Wrote あ.txt
```

**Expected result**
The file name becomes ".txt".

**Additional context**
In 1.94, the correct file name was output.

**Comment by AlDanial** [comment]
The file あ.txt can be written without problems on Linux but you're right, on Windows it is a problem.  However, it is not a problem with cloc but instead a problem with Perl on Windows.  This PowerShell session on Windows 11 demonstrates the problem.  First I create a regularly-named text file `abc.txt`,  then I try the same thing with `あ.txt`:
<pre>
PS C:\TEMP> perl -e "open(OUT, '>abc.txt'); print OUT 'hello'; close OUT"
PS C:\TEMP> type abc.txt
hello
PS C:\TEMP> perl -e "open(OUT, '>あ.txt'); print OUT 'hello'; close OUT"
PS C:\TEMP> type 'あ.txt'
type : Cannot find path 'C:\TEMP\あ.txt' because it does not exist.
  [...more errors...]
PS C:\TEMP> type あ.txt
type : Cannot find path 'C:\TEMP\あ.txt' because it does not exist.
  [...more errors...]
</pre>

I cannot explain why it worked with 1.94.  I updated Perl on Windows (Strawberry Perl) between 1.94 and now and possibly the problem came with that newer version.

If it is an option for you, try running in WSL?

**Comment by TomeSq** [comment]
Mr. AlDanial.
Thank you for the confirmation.

I was eventually able to solve the problem using the MINGW in the git bush and the perl script.

Thank you for taking the time to look into this.
