### ISSUE TITLE
Wrong code results for Java

### ISSUE THREAD

**Issue by PavelTurk** [AlDanial/cloc#806]
**Describe the bug**
Cloc doesn't count code lines in Java correctly.

**cloc; OS; OS version**
- cloc version: yesterday's
- If running the cloc source, Perl version: v5.30.0 built for x86_64-linux-gnu-thread-multi
- OS (eg Linux, Windows, macOS, etc): Linux
- OS version: Ubuntu 20.04.3 LTS

**To Reproduce**
This is a cut piece of code from Huffman class of Jetty project:

```
public class Huffman
{
    static final int[][] CODES =
        {
            /*'"' ( 34)  |11111110|01                         */        {0x3f9, 10},
            /*''' ( 39)  |11111111|010                        */        {0x7fa, 11},
        };
    // Huffman decode tree stored in a flattened char array for good
    // locality of reference.
    // Build the Huffman lookup tree and LC TABLE
}
```
When cloc counts this code its gives the following result:

```
github.com/AlDanial/cloc v 1.99  T=0.01 s (95.8 files/s, 1053.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Java                             1              0              0             11
-------------------------------------------------------------------------------
```
**Expected result**
There are only 8 code lines in the above piece.

**Additional context**

**Comment by AlDanial** [comment]
As described in https://github.com/AlDanial/cloc?tab=readme-ov-file#limitations- , cloc is an approximate tool since it does not parse each language's grammar.  Instead it uses relatively crude, but often effective, regular expressions.  The fix committed here won't work for more complicated entwinings of comments, strings, and text blocks.

This comment applies to #807 as well.  At some point the addition of ever more complex regexes won't be worth the performance penalty.
