### ISSUE TITLE
--not-match-d= includes file at root of pattern

### ISSUE THREAD

**Issue by njajones** [AlDanial/cloc#833]
**Describe the bug**
`--not-match-d=` excludes a folders subfolders, but not a file in that folder

**cloc; OS; OS version**
 - cloc version: 2.00
 - maxOS 14.5

**To Reproduce**
```
~ % mkdir Developer/clocTest
~ % mkdir Developer/clocTest/foo   
~ % mkdir Developer/clocTest/foo/bar
~ % echo "struct foo {\n}" > Developer/clocTest/foo/foo.swift 
~ % echo "struct bar { }" > Developer/clocTest/foo/bar/bar.swift 
~ % cd  Developer/clocTest 
clocTest % cloc . --fullpath --not-match-d="/foo/"
```

**Expected result**
I'd expect to filter out the files at `foo/foo.swift` and `foo/bar/bar.swift`
`0 text files response`

But instead get
```
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Swift                            1              0              0              2
-------------------------------------------------------------------------------
```
i.e. the results for `foo/foo.swift` with only `foo/bar/bar.swift` filtered out

**Additional context**
Actual result is the same as doing `cloc . --fullpath --not-match-d="bar"`.
Expected result can be achieved by doing `cloc . --fullpath --not-match-d="foo"` but for my actual real world use case I need to create a list of excludes i.e. ` cloc . --fullpath --not-match-d="/(root/example1|root/example2|root/example3)/"` such that `root/example1/file.swift` would be excluded as well as `root/example1/subfolder/file.swift`
This could just be a misunderstanding on how the regex works, as I've seen a number of other similar issues. However, I haven't found an answer that covers this case (AFAIK).

**Comment by njajones** [comment]
`-fullpath` is included above as it is needed (I believe) with my real world use case, but in the example above it makes no difference

**Comment by njajones** [comment]
The workaround in #732 also works in this case i.e. `cloc . -fullpath --not-match-d="/foo(/|$)" `

**Comment by AlDanial** [comment]
Yes, this is a bug.  If you run `find` in the `Developer` directory you'll see the same text that cloc will work on:
<pre>
~/Developer » find .
.
./clocTest
./clocTest/foo
./clocTest/foo/foo.swift
./clocTest/foo/bar
./clocTest/foo/bar/bar.swift
</pre>

The `./clocTest/foo` directory doesn't satisfy the `/foo/` pattern due to the missing trailing slash so the `foo` directory is accepted, and subsequently--incorrectly--its child file `foo.swift` is also accepted.

I need to add another check when examining files to make sure the parent directory doesn't match `--not-match-d`. (The #732 workaround allows `./clocTest/foo` to be rejected since it matches `/foo$`.)

**Comment by AlDanial** [comment]
Give ba6c1aa a try.

**Comment by njajones** [comment]
Works with my sample above. It's harder to test on my full project (as the use of cloc is quite deep in the code) but I'll give it a go

**Comment by njajones** [comment]
Fix works great. Thanks for the help

**Comment by AlDanial** [comment]
...and thanks for the contribution!
