### ISSUE TITLE
Not possible to strip comments and overwrite the original file?

### ISSUE THREAD

**Issue by wpccolorblind** [AlDanial/cloc#866]
**Describe the bug**
I have a large project with many subfolders and files.  I would like to run with --strip-comments but just update the original files.  It seems like there is only the option to create new files with a specified extension?

Desired behavior would be a method or option to update the original files, and not need to run a subsequent script to detect if a file has an accompanying extension, and deleting the original file, and renaming the cloc-outputted file to the original name.

Using:  cloc installed via homebrew on 11/2/2024.

**Comment by AlDanial** [comment]
That's right, there's no way to overwrite the original file minus the comments.  On Unix like operating systems (Linux, macOS, FreeBSD, etc) this can be done with the `find` and `xargs` commands: 

<pre>
cloc --original-dir --strip-comments=NO_COMMENT .
find . -type f -name "*.NO_COMMENT" | xargs -I {} sh -c 'mv "{}" $(echo "{}" | sed "s/\.NO_COMMENT$//")'
</pre>

I don't plan to fold this into cloc because `--strip-comments` is not perfect.  In particular it gets thrown off in languages like Java, C, C++ if the source files have strings that trick clock into thinking there are comment markers, for example `std::string X = "*/*.txt";`.  The resulting source will be broken.

**Comment by wpccolorblind** [comment]
Thank you! 

On Mac, I had to add an extra -S1024 to get that to work.

So:
`find . -type f -name "*.NO_COMMENT" | xargs -S1024 -I {} sh -c 'mv "{}" $(echo "{}" | sed "s/\.NO_COMMENT$//")'`
